### ISSUE TITLE
pppoe拨号能拨到外网ip，不能上网，要在防火墙-自定义规则里 重启防火墙 就可以上网。

### ISSUE THREAD

**Issue by 0533qz** [SuLingGG/OpenWrt-Rpi#1]
pppoe拨号能拨到外网ip，不能上网，要在防火墙-自定义规则里 重启防火墙 就可以上网。4.14.171

**Comment by SuLingGG** [comment]
(致访客)：
相似问题可以在此 Issues 中关注后续讨论：
<https://github.com/coolsnowwolf/lede/issues/3581>
并且建议尽量使用光猫拨号 (条件允许的情况下)
