### ISSUE TITLE
大佬能指点一下我怎么集成docker到固件里么？

### ISSUE THREAD

**Issue by guitoushayan** [SuLingGG/OpenWrt-Rpi#10]
我拉取lean大最新固件，编译时选择树莓派4b后不显示luci-app-dockerman这个选项，但是文件夹里可以搜的到，另外我重新下载luci-app-dockerman源码包(https://github.com/lisaac/luci-app-dockerman)复制到文件夹下之后，有luci-app-dockerman这个选项了
![2020-05-02 01-22-04 的屏幕截图](https://user-images.githubusercontent.com/26641693/80826151-50bcb380-8c14-11ea-9732-972f520c9839.png)
，但是不能选择上docker-ce，一选择docker-ce，luci-app-dockerman自动消失
![2020-05-02 01-23-11 的屏幕截图](https://user-images.githubusercontent.com/26641693/80826171-5b774880-8c14-11ea-8eb2-11cab91c3c41.png)另外我编译完的固件docker项目下只有一个概况
![2020-05-02 01-26-55 的屏幕截图](https://user-images.githubusercontent.com/26641693/80826235-7ba70780-8c14-11ea-80bc-5f7b92d1e497.png)

**Comment by SuLingGG** [comment]
首先删除存放在 packages 文件夹下 lisaac/luci-app-dockerman 的项目文件夹，删除完毕之后:

```
cd package
git clone --depth=1 https://github.com/KFERMercer/luci-app-dockerman
mkdir luci-lib-docker
curl -s -o ./luci-lib-docker/Makefile https://raw.githubusercontent.com/lisaac/luci-lib-docker/master/Makefile
rm -rf ../lean/luci-app-dockerman
```

之后回到 OpenWrt 源码根目录， `make menuconfig` 即可。

如果问题还未解决，在 OpenWrt 源码根目录执行: `rm -rf ./tmp && rm .config` (此操作会删除你 make menuconfig 生成的配置)，之后重新 `make menuconfig` 即可。

**Comment by guitoushayan** [comment]
感谢大佬指点，已经成功集成进固件了~
