### ISSUE TITLE
nanopi r4s 重启命令问题

### ISSUE THREAD

**Issue by OomelodyoO** [SuLingGG/OpenWrt-Rpi#100]
设备运行reboot -n，关机但不会再次启动

**Comment by SuLingGG** [comment]
可以试试 ext4 版本，群里有人说装了 ext4 版这个情况好像没有了...

**Comment by OomelodyoO** [comment]
> 可以试试 ext4 版本，群里有人说装了 ext4 版这个情况好像没有了...

大神您好，我安装的就是ext4版本
1.在公司用reboot是有效的，在家做主路由并拨号使用，发现执行reboot时，出现直接关机问题
2.在家openwrt管理后台 也经常不能打开了

**Comment by OomelodyoO** [comment]
https://github.com/coolsnowwolf/lede/issues/6184

**Comment by SuLingGG** [comment]
可以试试天灵 Dalao 的 https://t.me/nanopi_r2s 固件，
或者我的 OpenWrt-Mini 固件。

**Comment by OomelodyoO** [comment]
> 可以试试天灵 Dalao 的 https://t.me/nanopi_r2s 固件，
> 或者我的 OpenWrt-Mini 固件。

OpenWrt-Mini固件 哪里下载

**Comment by OomelodyoO** [comment]
> > 可以试试天灵 Dalao 的 https://t.me/nanopi_r2s 固件，
> > 或者我的 OpenWrt-Mini 固件。
> 
> OpenWrt-Mini固件 哪里下载
