### ISSUE TITLE
可否麻烦更新一下transmission web contral版本到1.61

### ISSUE THREAD

**Issue by ricksuzade-maker** [SuLingGG/OpenWrt-Rpi#102]
每次进去都会提示有新版，我自己尝试了更新，但是一直没找到正确的方法，麻烦作者有空的时候帮忙更新下，谢谢！

**Comment by SuLingGG** [comment]
这个没有办法，更新之后就完全没法用啦，所以不管是我还是 Lean 那边都没有更新。

**Comment by SuLingGG** [comment]
这个没有办法，更新之后就完全没法用啦，所以不管是我还是 Lean 那边都没有更新。
