### ISSUE TITLE
系统日志能不能改成时间倒序啊，每次看日志都要翻到底

### ISSUE THREAD

**Issue by youyifentian** [SuLingGG/OpenWrt-Rpi#104]
系统日志能不能改成时间倒序啊，每次看日志都要翻到底

**Comment by SuLingGG** [comment]
你这个需求比较特殊...我这里暂时不会考虑对 LuCI 组件进行更改，建议你配合终端来实现:

SSH 登录 OpenWrt 的终端，执行 `dmesg` 可以查看内核日志，执行 `logread` 可以查看系统日志；

执行:

```
dmesg | tail -n 20
```

可以查看内核日志末尾后 20 行，同理执行:

```
logread | tail -n 20
```

可以查看系统日志末尾 20 行。

**Comment by youyifentian** [comment]
好的，谢谢啦
