### ISSUE TITLE
关于无线网络的问题

### ISSUE THREAD

**Issue by lyl15151865258** [SuLingGG/OpenWrt-Rpi#105]
请教一下，在网络页面里面，没有找到无线模块，是没有添加进去吗？

**Comment by SuLingGG** [comment]
现在项目已经支持很多设备，提 Issues 请先说明你用的是哪些设备。
同时需要说明白具体场景，比如设备板载无线网卡，但是在控制面板没有显示“无线”菜单；
或者是设备没有板载无线网卡支持，你想通过外接 USB 设备进行无线上网。
你如果说不清楚，那我是没办法解决的。

**Comment by lyl15151865258** [comment]
您好，我使用的是友善之臂R4S（4G内存版本），使用两个USB无线网卡（RTL8812BU），其官方固件是带无线功能的，且支持我这个无线网卡，但是官方固件插件太少，第三方固件我尝试刷写了一部分，都没有看到有“无线”菜单，所以想咨询一下是由于没有该网卡型号的驱动呢还是没有添加无线功能呢？谢谢！
![image](https://user-images.githubusercontent.com/24789943/112096156-b329f400-8bd8-11eb-8a13-eb36b00b15c7.png)

**Comment by AmadeusGhost** [comment]
驱动有的，自己加进去吧：https://github.com/immortalwrt/immortalwrt/tree/master/package/kernel/rtl88x2bu ，不过据说只能在 legacy 模式下工作

**Comment by lyl15151865258** [comment]
感谢大佬，可惜我不会加，我只会用，哈哈
