### ISSUE TITLE
希望加入2.5GUSB网卡RTL8156B的驱动

### ISSUE THREAD

**Issue by maybeloveu** [SuLingGG/OpenWrt-Rpi#106]
最近买了RTL8156B的usb网卡，可惜群晖插上在虚拟机找不到网络。想用在树莓派4B上，配合AX6000对接2.5G网络体验一下。希望大大考虑加入这个网卡的驱动

**Comment by SuLingGG** [comment]
看 Lean 那边的 Issues，好像我的固件已经集成这个驱动了，你可以插上这块网卡后在 网络 - 接口 - 添加新接口 中查看是否有 eth1 出现，如果有的话说明这块网卡已经被识别了。

**Comment by maybeloveu** [comment]
试过了不行

**Comment by SuLingGG** [comment]
那我这里也没有啥办法了...

**Comment by longdahai** [comment]
我也是4b试了最新版可以识别，但传输会断流测速连千兆都达不到，等修复了

**Comment by maybeloveu** [comment]
> 我也是4b试了最新版可以识别，但传输会断流测速连千兆都达不到，等修复了

期待修复版本！
