### ISSUE TITLE
关于无线网络

### ISSUE THREAD

**Issue by youyifentian** [SuLingGG/OpenWrt-Rpi#107]
第一个疑问：我装的是x86-64系统，内置无线wifi，用无线的扫描功能可以扫描的2.4G和5G的wifi，但是开启wifi只能开启2.4G的，设置5G的任何信道都不行，开启不了，没有信号，另外选择国家代码中，选US和CN出来的信道都一样，信道选择列表没有变化，这个正常吗？

第二个bug，就是当我新建一个无线2.4G，然后点停用之后，在打开概况页面时CPU会狂飙，只要打开这一个页面会这样，切换到其他页面CPU立马回复正常，或者启用wifi后也正常，这是bug吗，

**Comment by SuLingGG** [comment]
按理说不应该出现这些问题，但是因为 Linux 的无线驱动...你也懂的 (尤其是对于部分螃蟹卡来说)，出现一些奇奇怪怪的 Bug 也无法避免...
