### ISSUE TITLE
支持zero

### ISSUE THREAD

**Issue by YeautyYE** [SuLingGG/OpenWrt-Rpi#108]
我用raspberry os的时候网络特别慢，无论在zero还是4b上。
但我想用zero做一些别的事情，显然openwrt在网络传输上非常有优势（我有个4b的openwrt）
希望能支持

**Comment by SuLingGG** [comment]
This project support Raspberry Pi zero/zero W/1b/2b/3b/3b+/4b.

If you want to use firmware of zero/zero W, You can flash firmware of Raspberry Pi 1B directly.

If you want to run OpenWrt over Docker, You can move to this project:

<https://github.com/SuLingGG/OpenWrt-Rpi-Docker>

为什么要打英文，因为我觉得你上面这段话是机翻的...

**Comment by YeautyYE** [comment]
lol~ Think you.
