### ISSUE TITLE
BaiduPCS-Web中的小bug

### ISSUE THREAD

**Issue by youyifentian** [SuLingGG/OpenWrt-Rpi#109]
BaiduPCS-Web本身在openwrt中使用是可以正常运行的，但是，当使用frp内网穿透时，如果定义的远程端口不是80，比如是：远程frp的openwrt网址是http://openwrt.remote.com:，端口：5678，那就会在BaiduPCS-Web中打开管理页面时js脚本报错

baidupcs-web:133 Uncaught DOMException: Failed to execute 'open' on 'Window': Unable to open a window with invalid URL 'http://openwrt.remote.com:5678:5299/'.

    at openClient (http://openwrt.remote.com:5678/cgi-bin/luci/admin/nas/baidupcs-web:133:9)
    at HTMLInputElement.onclick (http://openwrt.remote.com:5678/cgi-bin/luci/admin/nas/baidupcs-web:1:1)

定位错误代码如下：
function openClient() {
	var curWwwPath = window.document.location.href;
	var pathName = window.document.location.pathname;
	var pos = curWwwPath.indexOf(pathName);
	var localhostPath = curWwwPath.substring(0, pos);
	var clientPort = window.document.getElementById("cbid.baidupcs-web.config.port").value
	var url = "http:" + localhostPath.substring(window.location.protocol.length) + ":" + clientPort;
	window.open(url)
};

应该BaiduPCS-Web在获取管理地址的时候直接加了端口号，而没有把openwrt管理页面地址原有的端口号去掉，比如直接手动访问：http://openwrt.remote.com:5299/，就可以直接进入BaiduPCS-Web的管理页面，希望能修复下上面的代码！

**Comment by SuLingGG** [comment]
谢谢你分享这个问题的解决方案~

但是这个项目的源码至今长期无人维护以至于处于接近不能用的状态，我之前已经打算在固件里移除这个包了，至今没有移除的原因是部分使用者确实依赖这个功能，所以暂时没有移除...

所以我这边暂时不会对这个包做额外的处理了。
