### ISSUE TITLE
R4s 固件版本不再马按照1G和4G分别发布？

### ISSUE THREAD

**Issue by fusuku** [SuLingGG/OpenWrt-Rpi#110]
Su大，请教个问题，是不是自3月18日以后，R4s的固件将不再分为1G和4G版本。若系统内升级（非刷卡）的时候固件名字时候还需要改为和之前带版本的固件名称一致？否则系统提示“固件版本不通用”。谢谢答复

**Comment by SuLingGG** [comment]
是的，现在 R4S 已经不区分 1G 和 4G 固件了，但是本项目固件在升级上暂时还是有点问题。暂时不支持 web 页面升级。如果有升级需求建议重刷固件。

**Comment by fusuku** [comment]
> 是的，现在 R4S 已经不区分 1G 和 4G 固件了，但是本项目固件在升级上暂时还是有点问题。暂时不支持 web 页面升级。如果有升级需求建议重刷固件。

谢谢大佬回复！orz 辛苦了！
