### ISSUE TITLE
树莓派4无法使用docker-compose

### ISSUE THREAD

**Issue by kingzleshe** [SuLingGG/OpenWrt-Rpi#111]
找不到相关issue， 是不支持吗？
安装了相关docker-compose软件包后，执行docker-compose命令就报python相关错误

**Comment by SuLingGG** [comment]
从软件源安装的 docker-compose 无法与本固件兼容，我已经尝试集成了 docker-compose，可以刷一下明天的固件试试看。

**Comment by kingzleshe** [comment]
好的

**Comment by CodeDreamfy** [comment]
我之前使用python3在大佬的openwrtmini固件上面安装成功了docker-composee了
