### ISSUE TITLE
RTL8812AU网卡一直在2.4G和5G切换，无法连接。找过很多驱动不会搞

### ISSUE THREAD

**Issue by wwsq1149** [SuLingGG/OpenWrt-Rpi#112]
我注意到这句话：“⚠️虽然固件添加了 kmod-rtl8812au-ct 驱动，但此驱动下的网卡无法被 LuCI 控制 (可能需要在 CLI 下使用)。”
有什么解决方法吗
我在网上找到了一些驱动（不会编译）

**Comment by SuLingGG** [comment]
按理说这块网卡已经可以在最新版固件使用了，你刷的是最新版固件吗？

**Comment by wwsq1149** [comment]
是吗，我下次再刷一个新的试试，谢谢~

**Comment by wwsq1149** [comment]
还是不行
![image](https://user-images.githubusercontent.com/70135780/113478260-638dd700-94ba-11eb-84bd-0141a751831e.png)
5G差不多是这样的：（不是这个网卡的图，模式是Client）
![image](https://user-images.githubusercontent.com/70135780/113478269-7c968800-94ba-11eb-8859-5cfa2c82a88d.png)

**Comment by AmadeusGhost** [comment]
这块网卡的驱动应该是用 kmod-rtl8812au-ac 而不是 kmod-rtl8812au-ct（2 个驱动只能选 1 个安装进去）。
