### ISSUE TITLE
競鬥雲project 版本的內核還是4.14

### ISSUE THREAD

**Issue by changchichung** [SuLingGG/OpenWrt-Rpi#12]
我從readme 的連結進去到 https://github.com/SuLingGG/OpenWrt-Rpi/actions/runs/131294656
下載之後，進入 opboot 刷，是可以刷成功
但是內核版本還是4.14 不是 5.4 呀？

**Comment by SuLingGG** [comment]
从与固件一同提供的 `openwrt-ipq40xx-p2w_r619ac.manifest` 文件中可以看出，与内核相关的包都是 5.4.45 版本的，应该没有问题。等我下班回去试试看~

**Comment by SuLingGG** [comment]
刚刚测试了一下，我这里没有问题:
