### ISSUE TITLE
Open Wrte 网络共享 遇到设置问题

### ISSUE THREAD

**Issue by chan2093** [SuLingGG/OpenWrt-Rpi#120]
OpenWrt 网络共享 设置遇到问题。请问怎么设置用户名？尝试使用了root以及默认密码仍然无法登入。
![Capture](https://user-images.githubusercontent.com/47651746/114293824-f981bd00-9acb-11eb-8a00-78cea8fb11d9.PNG)
![Capture2](https://user-images.githubusercontent.com/47651746/114293851-449bd000-9acc-11eb-879c-251557e6c540.PNG)
恳请指导，谢谢。

**Comment by EnnawYang** [comment]
请使用 `smbpasswd` 添加用户及密码，使用root用户共享请注释掉 `invalid users = root` 字段

**Comment by chan2093** [comment]
请问是在TTYD终端 添加吗？

**Comment by EnnawYang** [comment]
> 请问是在TTYD终端 添加吗？

`smbpasswd -a` 是在ssh中执行， `invalid users = root` 是在模版中编辑

**Comment by chan2093** [comment]
![Capture](https://user-images.githubusercontent.com/47651746/114294314-4e273700-9ad0-11eb-9179-71d536ac491d.PNG)
我会遇到无法添加的问题...

**Comment by chan2093** [comment]
已经可以了。需要在系统里添加用户。
