### ISSUE TITLE
transmission 使用一段时间后出现红种问题

### ISSUE THREAD

**Issue by 461720777** [SuLingGG/OpenWrt-Rpi#121]
刚开始做种使用正常，一段时间后出现大面积红种
配置上应该没有问题，已经下载了600G+资源，今天突然大面积显示no space left on device。
下载目录配置正确，inode占用率很低，限速至低于USB2.0的速度，修改目录权限。
以上方案均已尝试，依然没有解决。
同时不是全部红种，范围是全部的下载中的种子和部分下载完成的种子。
每次红种后，下载的数据不会丢失，只是停止下载。
希望能够解决。

**Comment by 461720777** [comment]
设备是R2S ext4

**Comment by SuLingGG** [comment]
变量太多。
SD 卡体质，供电，NanoPi 的辣鸡供电以及静电问题，外接设备体质，连接线，存储介质，PT 提供商，宽带服务商限制。
建议自行一一排查。
或者你可以试试换张 SD 卡刷入固件，如果还是出现这个问题再反馈。
