### ISSUE TITLE
AdGuard Home无法进入管理页面

### ISSUE THREAD

**Issue by xuzheliang135** [SuLingGG/OpenWrt-Rpi#122]
正常安装在树莓派上之后，开启AdGuard Home，使用默认配置（仅5553重定向选择使用53端口替换dnsmasq）。
显示开启成功后，访问`http://192.168.1.1:3000/`，被重定向到`http://192.168.1.1:3000/login.html`，网页显示`404 page not found`。
使用的版本为2021/4/11号的树莓派3B/3B+版本 lean版本

**Comment by SuLingGG** [comment]
强制更新一次 Adguardhome 二进制文件应该可以解决。
"更新核心版本 -> 强制更新"

**Comment by xuzheliang135** [comment]
多谢！已解决！
