### ISSUE TITLE
R2S使用中断电有一定概率导致/dev/root为只读文件系统

### ISSUE THREAD

**Issue by 461720777** [SuLingGG/OpenWrt-Rpi#126]
fsck.ext4 命令可以修复，不知道能不能做成自动的脚本。
一个月内出现两次该问题。

同时，
发现直接指向/dev/root会显示不存在
/dev/mmcblk0p2可以。

**Comment by SuLingGG** [comment]
这个是老问题了，可以尝试换成 squashfs 固件试试看。
