### ISSUE TITLE
状态栏怎么看不到CPU分数？已经安装了coremark

### ISSUE THREAD

**Issue by JackJie-J** [SuLingGG/OpenWrt-Rpi#129]

**Comment by Nlqqer** [comment]
@JackJie-J 看readme

**Comment by SuLingGG** [comment]
ssh 或者 ttyd 中执行 `/etc/coremark.sh` ，等待命令执行完 (可能需要 1~2 分钟) 即可在 LuCI 首页看到分数。
如果你直接执行 `coremark` 会在终端中输出跑分结果 (同样需要等待 1~2 分钟) 。
实际上 `/etc/coremark.sh` 会在每天凌晨 4:00 执行，你还也可以什么都不做，静静等到明天早晨，让跑分结果自动显示到 LuCI 首页。

**Comment by JackJie-J** [comment]
感谢苏ling大佬解答！致敬
