### ISSUE TITLE
树莓派4能不能加入USB网卡驱动，谢谢！

### ISSUE THREAD

**Issue by fjqzaxljm** [SuLingGG/OpenWrt-Rpi#130]

**Comment by EnnawYang** [comment]
@fjqzaxljm 先不说能不能加吧，型号总得给一个吧？

**Comment by fjqzaxljm** [comment]
> @fjqzaxljm 先不说能不能加吧，型号总得给一个吧？

RTL8153

**Comment by EnnawYang** [comment]
> > @fjqzaxljm 先不说能不能加吧，型号总得给一个吧？
> 
> RTL8153

https://github.com/SuLingGG/OpenWrt-Rpi/blob/main/config/bcm27xx/rpi-lean-extra.config#L51
8153应该是支持的（RTL8152驱动）

**Comment by xtellaris** [comment]
> > @fjqzaxljm 先不说能不能加吧，型号总得给一个吧？
> 
> RTL8153

8153支持的，我这里已经用了3个月了
