### ISSUE TITLE
有什么无线网卡推荐

### ISSUE THREAD

**Issue by wwsq1149** [SuLingGG/OpenWrt-Rpi#133]
适合这个固件的
支持5G
最好有功放
某宝找半天没找到

**Comment by EnnawYang** [comment]
建议买硬路由

**Comment by SuLingGG** [comment]
建议读完文档再来提问。

**Comment by wwsq1149** [comment]
@SuLingGG 我之前看过了，主要是要信号好的，有增益的，所以才提问，刚刚看了 网件 A6210 拆解 有看到功放，请问信号实际体验怎样？

**Comment by SuLingGG** [comment]
> @SuLingGG 我之前看过了，主要是要信号好的，有增益的，所以才提问，刚刚看了 网件 A6210 拆解 有看到功放，请问信号实际体验怎样？

保守估计穿一堵普通墙的水平吧...

**Comment by wwsq1149** [comment]
@SuLingGG 谢谢

**Comment by wwsq1149** [comment]
@SuLingGG 还有一个小小的问题，接收时的信号好吗，可否和手机之类的对比一下？

**Comment by SuLingGG** [comment]
@wwsq1149 买回来自己试一下吧...
闲鱼 100 以内就能入手，如果不喜欢再出掉就是了。
如果还是满足不了你的需求建议直接买个 USB 有线网卡接个路由器。
