### ISSUE TITLE
默认没有集成 openssh-server

### ISSUE THREAD

**Issue by Erich-Chen** [SuLingGG/OpenWrt-Rpi#134]
注意到您的配置文件中没有安装 openssh-server，因此无法 ssh 到 OpenWrt 中。
（可以在 Luci 界面上找到 TTYD 代替）
不知是否由于安全原因，或者其它的考虑？

解决方案也是很明显的。

i) 自行编译，至少添加一行：

`CONFIG_PACKAGE_openssh-server=y`

ii) 烧录之后，手工安装：

在 LuCI 界面，“系统 > TTYD 终端"，执行：

`opkg update`

`opkg install openssh-server`

**Comment by EnnawYang** [comment]
难道没有 `Dropbear ` ？

**Comment by SuLingGG** [comment]
OpenWrt 的 SSH 默认由 dropbear 提供。
为了不再重复我就没装 openssh。
另外我的固件 ssh 应该是没问题的，如果你那边有问题建议重刷固件再试。

**Comment by Erich-Chen** [comment]
> OpenWrt 的 SSH 默认由 dropbear 提供。
> 为了不再重复我就没装 openssh。
> 另外我的固件 ssh 应该是没问题的，如果你那边有问题建议重刷固件再试。

谢谢！我下载新编译的固件重刷一下。
此 ticket 到此可以关闭，感谢快速回复。

**Comment by SuLingGG** [comment]
只要固件的软件包里有 dropbear 这个包那 ssh 应该是没问题的。
不过我也没办法排除确实出 bug 的可能...
你试试看吧~
