### ISSUE TITLE
请教，DNS Servers 以及DHCP Server怎么设定为8.8.8.8 &8.8.4.4

### ISSUE THREAD

**Issue by chan2093** [SuLingGG/OpenWrt-Rpi#136]
我遇到一个问题，由于IPS有过滤一些网站访问的功能，平时我都在路由器WIFI的DHCP下手动设定成 DNS server 为8.8.8.8以及8.8.4.4绕过IPS过滤器。请问OpenWrt下的DHCP修改后为什么不能更改终端接收到的DNS Servers为8.8.8.8以及8.8.4.4。
或许本人设定上有错，请求指导。谢谢。
请参阅附图
![Capture](https://user-images.githubusercontent.com/47651746/116486756-ee4ad180-a8c0-11eb-9265-b8ad9e5fcc29.PNG)
需要修改的DNS Server
![Capture2](https://user-images.githubusercontent.com/47651746/116486780-f99dfd00-a8c0-11eb-89ba-31961b93ca92.PNG)
手动设定但无效
![Capture3](https://user-images.githubusercontent.com/47651746/116486809-0c183680-a8c1-11eb-8ea5-b5aec2478c9b.PNG)
需要手动设定，但手机就不好使了。

**Comment by SuLingGG** [comment]
需要在
网络 - 接口 - Lan - 修改
中修改 DNS，这样 DNS 配置才能随 DHCP 直接下发到设备。

**Comment by chan2093** [comment]
![Capture](https://user-images.githubusercontent.com/47651746/116555329-d6119b80-a92e-11eb-8511-f14f1e397f59.PNG)
![Capture2](https://user-images.githubusercontent.com/47651746/116555342-db6ee600-a92e-11eb-97df-893c65598a67.PNG)
不好意思，我尝试了但仍然修改不到。WIFI的DHCP里的DNS仍然是192.168.1.1

**Comment by SuLingGG** [comment]
重启试试。另外这些设置仅在 OpenWrt 作为 DHCP 服务器时才生效，如果你把 OpenWrt 作为不开启 DHCP 的旁路由之用，那当然不会生效。

**Comment by we2oxy** [comment]
> ![Capture](https://user-images.githubusercontent.com/47651746/116555329-d6119b80-a92e-11eb-8511-f14f1e397f59.PNG)
> ![Capture2](https://user-images.githubusercontent.com/47651746/116555342-db6ee600-a92e-11eb-97df-893c65598a67.PNG)
> 不好意思，我尝试了但仍然修改不到。WIFI的DHCP里的DNS仍然是192.168.1.1

![Snipaste_2021-04-29_21-27-02](https://user-images.githubusercontent.com/45049572/116558238-ccd5fe00-a931-11eb-8862-77f8a4ef15cb.jpg)

**Comment by SuLingGG** [comment]
对，也可以试试楼上 Dalao 的方法 (

**Comment by chan2093** [comment]
![Capture](https://user-images.githubusercontent.com/47651746/116565297-4f61bc00-a938-11eb-9a34-b428f7f8a41d.PNG)
行了，非常完美，谢谢dalao。
