### ISSUE TITLE
Docker的一个小问题

### ISSUE THREAD

**Issue by wwsq1149** [SuLingGG/OpenWrt-Rpi#137]
在pull一个比较大的镜像时，不知道是浏览器超时还是怎么样，就502BadGateway了
![image](https://user-images.githubusercontent.com/70135780/116532962-6d68f580-a913-11eb-915c-4a2f1a9be69e.png)
只能用命令行重新下载一遍

顺便问一下，我把web服务的端口改成100，但是80/443端口还是有占用
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      4713/uci.conf -g da
是nginx的配置/etc/nginx/uci.conf
怎么解决，我想把网站部署到80/443端口

**Comment by SuLingGG** [comment]
uhttpd 是有等待超时时间限制的，如果你在拉取镜像的过程中超过规定的时间没有返回，uhttpd 就会报错。
Nginx 是可道云的依赖，如果你用不到可道云，可以卸载掉可道云和固件内的 Nginx。
