### ISSUE TITLE
pppoe拨号经常断线

### ISSUE THREAD

**Issue by swbbs1982** [SuLingGG/OpenWrt-Rpi#138]
pppoe 拨号经常断线，不重拨，多次点击链接不成功。
链接pc 拨号，很快，链接断开多次都没问题。

**Comment by SuLingGG** [comment]
我这里没办法优化这个问题。我这里也没有 PPPoE 拨号环境可供测试。建议用更稳定的设备进行拨号。

**Comment by swbbs1982** [comment]
r4s 上个星期之前使用一直都很稳定，昨天的新版本开始，出这个pppoe 不连接，断线不重连

**Comment by SuLingGG** [comment]
我这里也没有 R4S... 并且最近没有更改过与 R4S 有关的东西。如果你说的问题确实存在，那可能是源码层面的问题。

**Comment by neil-wu** [comment]
我这之前出现过断线的问题，是mwan引起的，删除后就稳如狗。 可以试试 ：[参考链接](https://github.com/SuLingGG/OpenWrt-Rpi/issues/99)
