### ISSUE TITLE
SuLing GG您好，R4S的LAN口插网线的网络指示灯，目前只有黄灯亮，绿灯不良，连续刷了好几个不同日期的固件，都有这个问题

### ISSUE THREAD

**Issue by yangwen9** [SuLingGG/OpenWrt-Rpi#145]
SuLing GG您好，R4S的LAN口插网线的网络指示灯，目前只有黄灯亮，绿灯不良，连续刷了好几个不同日期的固件，都有这个问题

**Comment by MatinxHT** [comment]
@yangwen9 千兆模式亮黄灯，百兆模式亮绿灯

**Comment by yangwen9** [comment]
@Mention ***@***.***>谢谢解答疑惑，我昨天又试了一下Kelever
1988的R4S固件，Lan口黄灯和绿灯是全亮的，不清楚针对网口亮灯这块是怎么编译的，是源码默认的规则，还是后续编译修改的

Martin ***@***.***> 于 2021年5月13日周四 12:38写道：

**Comment by YinhaoHe** [comment]
Same issue here. just to mention
