### ISSUE TITLE
zerotier引起系统负载过高

### ISSUE THREAD

**Issue by Licsber** [SuLingGG/OpenWrt-Rpi#146]
系统负载变化曲线如下：
![85E254519C37C1FD0DA619B61A979AC6](https://user-images.githubusercontent.com/19817606/118242344-d0d85300-b4cf-11eb-8afb-080338b488db.jpg)

出问题的现象：以下进程大量增加
sh -c config .... /etc/zerotier.start
目前没找到在哪里出现的这个调用
截图如下
![16-24-38](https://user-images.githubusercontent.com/19817606/118243486-12b5c900-b4d1-11eb-890f-7c8d474c582e.png)

解决方案 killall sh
强行终止所有sh进程
目前暂时无法复现 希望有路过的大佬看看哪里出了问题

**Comment by SuLingGG** [comment]
建议你去 https://github.com/coolsnowwolf/lede/issues 反馈一下。

**Comment by Licsber** [comment]
![15-12-04](https://user-images.githubusercontent.com/19817606/118352360-a6e86480-b593-11eb-96ad-933e6d5fe956.png)
更新：
冤枉好人了 问题出在zerotier上
/etc/zerotier.start脚本有问题
会卡在iptables的配置上
由于mwan3的ifup事件会调用fw3 -q reload
其会调用/etc/zerotier.start 导致所有hotplug都卡在这里
目前解决方案为关闭zerotier
此issue等待上游解决
