### ISSUE TITLE
请教3B+ WiFi 频繁中断

### ISSUE THREAD

**Issue by nemo2018** [SuLingGG/OpenWrt-Rpi#147]
各位好，
今天使用最新的固件，树莓派3B+上刷好，计划做旁路由，但是要用树莓派自带的WiFi做热点。
只打开openclash，其他都不动。
Su大的固件已经使用在其他设备使用很久，openclash使用很熟悉，配置好启动都正常。

使用了一阵发现每隔几分钟，电脑的WiFi就要断一下，去看了日志发现有如下不正常记录。
试着Google了一下，尝试了几个地方都没有改善。
请问我们有同样使用场景的朋友遇到类似问题么？
谢谢！
![image](https://user-images.githubusercontent.com/37334053/118526759-25e7c380-b773-11eb-88da-ffcae43e8fa2.png)

**Comment by SuLingGG** [comment]
你有可能启用了无线加密并且启用了一些高级的 802.11x 特性。
试试关闭无线加密，或者尝试将无线加密相关设置修改为如图所示设置:

![image](https://user-images.githubusercontent.com/22287562/118656279-f68d9100-b81c-11eb-8d14-fe50d3b48bf6.png)

在某些设备上启用无线加密会出现一些不可预知的问题，建议不为热点设置密码。如果必要，可以将 SSID 隐藏。

**Comment by nemo2018** [comment]
感谢大佬回答。我按照上述建议的设置了无线加密，依旧。
不过没关系了，我改变了用法，用无线做了wwan，lan接电脑上，反正我只是给一台有网口的电脑用而已。
再次感谢！
