### ISSUE TITLE
关闭树莓派的指示灯

### ISSUE THREAD

**Issue by kuroidark** [SuLingGG/OpenWrt-Rpi#150]
大家好，有人知道这个固件下如何关闭所有的指示灯么？在树莓派官方的固件里可以在config.txt中加入以下内容实现关灯的效果，不知道这个固件有没有办法关掉？

```
# Turn OFF Network LED's
dtparam=eth_led0=14
dtparam=eth_led1=14

# Turn OFF Power LEDs
dtparam=act_led_trigger=none
dtparam=pwr_led_trigger=none
```

**Comment by kuroidark** [comment]
设备是树莓派4b，lean版固件

**Comment by kuroidark** [comment]
用绝缘胶给他贴起来了

**Comment by SuLingGG** [comment]
![image](https://user-images.githubusercontent.com/22287562/120185433-c72b4b00-c244-11eb-8299-b68a7f388f7a.png)

如上图设置即可。

**Comment by kuroidark** [comment]
> ![image](https://user-images.githubusercontent.com/22287562/120185433-c72b4b00-c244-11eb-8299-b68a7f388f7a.png)
> 
> 
> 
> 如上图设置即可。

这个是无效的，只能关闭电源灯XD

**Comment by kuroidark** [comment]
> 我这儿都都正常关闭...但是也有可能是我在用 Mini 固件的原因。

好的，我改天用我的另一个树莓派3b刷mini固件测试下~
