### ISSUE TITLE
MINISFORUM GK50 主机兼容问题

### ISSUE THREAD

**Issue by yangwen9** [SuLingGG/OpenWrt-Rpi#153]
SuLing GG你好， X86的固件不兼容MINISFORUM的最新GK50小主机，首先是刷系统后，Lan口接电脑不识别，手动改IP地址后，可以登录后台，但是WAN口没法和外网联通，偶尔连接OK可以上网，但是只要重启或者断电，后面在也没法识别网络了，目前的固件，Beelink GK55的小主机兼容效果蛮好的， 这个具体是什么原因？有没有研究过，按理说都是X86的小主机，对固件的匹配程度应该也是没有什么差异的？

**Comment by SuLingGG** [comment]
我没办法对每个设备都做兼容处理。
另外我没有你所说的这一型号小主机，所以暂时也无能为力。
