### ISSUE TITLE
能否添加MBIM modem的支持

### ISSUE THREAD

**Issue by bigcachetx** [SuLingGG/OpenWrt-Rpi#154]
同时加入modemmanager？

**Comment by SuLingGG** [comment]
需要添加的包有哪些呢？
我这边没有蜂窝数据设备，所以暂时也没办法测试。
但你可以列出需要添加的软件包，我随后添加进固件。

**Comment by bigcachetx** [comment]
有个英文固件有，但是他们没有集成我们爱用的那些软件包。
他们也给出了需要的包
https://www.ofmodemsandmen.com/buildpkg.html

在GitHub也有说明 https://openwrt.org/docs/guide-user/network/wan/wwan/modemmanager

**Comment by bigcachetx** [comment]
https://github.com/linux-mobile-broadband/libmbim

**Comment by bigcachetx** [comment]
https://github.com/linux-mobile-broadband/ModemManager

**Comment by SuLingGG** [comment]
抱歉最近事务繁忙。已于 https://github.com/SuLingGG/OpenWrt-Rpi/commit/dc2592adb42faaaedeaec49de673b6dbcc3afa8f 添加了 modemmanager 和 luci-proto-modemmanager 支持，你也许可以直接从 luci 界面配置 modemmanager，当然原始方法应该也是可以的，我这边没有条件测试，等新固件释出你可以试试看~

**Comment by bigcachetx** [comment]
多谢！等出来了下载试试。
