### ISSUE TITLE
意外断电后系统出现“ready-only file system”

### ISSUE THREAD

**Issue by SweetJava** [SuLingGG/OpenWrt-Rpi#155]
固件版本 ："openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz" 
问题描述：1、系统无法进行磁盘的读写操作（touch,cp,chmod）等等
                  2、系统各项服务无法启动
                  3、只有涉及到系统磁盘的写操作，都会报错"Read-only file system"
问题原因：猜测为断电意外关机，重启后系统文件变成了只读。

目前使用 e2fsck 修复后重启恢复，但断电重启后依然会出现此问题。

系统曾使用GParted扩容
# root @ OpenWrt in ~ [19:28:38] 
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0 117.8G  0 disk 
├─mmcblk0p1 179:1    0    64M  0 part /mnt/mmcblk0p1
└─mmcblk0p2 179:2    0 117.6G  0 part /

**Comment by SuLingGG** [comment]
这个问题其实是老生常谈了，建议换用用 squashfs 的固件试试，同时在刷固件之前建议先按:

https://openwrt.cc/restore/

里面的说明先刷一下恢复固件，然后再刷 OpenWrt 固件试试。
