### ISSUE TITLE
为啥 x86 的没有 led配置 功能呢?软件包里也搜索不到

### ISSUE THREAD

**Issue by NewGreenHand** [SuLingGG/OpenWrt-Rpi#157]
我用精简版(mini)的树莓派固件上面都有这个插件, 能添加一下嘛(那LED灯真的很闪, 晚上就是光污染)

**Comment by AmadeusGhost** [comment]
你的 x86 设备估计不支持，直接拿胶布封上吧。

**Comment by NewGreenHand** [comment]
别呀, 我就是想把电源灯关了而已, 这个大概率是支持的

**Comment by SuLingGG** [comment]
这个功能是被捆绑在 LuCI 套件里的，不能以软件包的形式安装，如果 OpenWrt 检测到你的硬件支持 LED 控制那么就会显示这个菜单，如果硬件的 LED 控制不被 OpenWrt 支持那就不会被显示。
综上所述还是用黑胶带吧，如果你想美观一些可以在淘宝购买黑色的碳纤维汽车贴纸，用来遮光很好用，而且很美观。

**Comment by NewGreenHand** [comment]
> 这个功能是被捆绑在 LuCI 套件里的，不能以软件包的形式安装，如果 OpenWrt 检测到你的硬件支持 LED 控制就会立即显示这个菜单，如果硬件的 LED 控制锁定 OpenWrt 支持不会显示。
> 综上所述还是用黑九吧吧，如果你想好看一些可以在淘宝买黑色的碳纤维汽车贴纸，遮光好用，而且很漂亮。

好好, 谢谢

**Comment by lxl6125** [comment]
@NewGreenHand 一只黑色油性笔解决😏

**Comment by NewGreenHand** [comment]
> @NewGreenHand三款黑色油性笔解决😏

可以试试
