### ISSUE TITLE
求添加玩客云的固件

### ISSUE THREAD

**Issue by dreamskr** [SuLingGG/OpenWrt-Rpi#158]
如题，求添加玩客云的固件，谢谢

**Comment by SuLingGG** [comment]
玩客云虽然是很热门的设备，但是这个设备像 N1 一样暂时不被 OpenWrt 源码支持，所以暂时不会被添加。
你也可以提取玩客云能用的 armbian 固件里面的的 dtb 文件，替换到相同或者类似 CPU 架构的 OpenWrt 固件里刷入试试。
