### ISSUE TITLE
nanopi r4s lan 口Led灯不亮

### ISSUE THREAD

**Issue by YinhaoHe** [SuLingGG/OpenWrt-Rpi#160]
minor issue - any possible fix?

**Comment by new1943** [comment]
我好像也是，换了好几个固件都是，说可能是硬件问题

**Comment by YinhaoHe** [comment]
> 我好像也是，换了好几个固件都是，说可能是硬件问题

我重新自己编译了 Lean的openwrt 没有遇到相同问题了，而且看到网上有人提SuLingGG的固件是千兆亮黄灯，百兆是绿灯。我没有确认过这个问题，我选择自己编译了固件，解决了这个不亮的情况，确认了不是nanopi r4s 硬件问题。我是openwrt 21 编译的，感觉openwrt 21 或者 18 snapshot 都挺稳定。
