### ISSUE TITLE
可否为qBittorrent更换第三方UI，对手机版支持良好

### ISSUE THREAD

**Issue by tiandongxv** [SuLingGG/OpenWrt-Rpi#167]
https://github.com/CzBiX/qb-web

**Comment by EnnawYang** [comment]
@tiandongxv 你可以直接用手机app

**Comment by SuLingGG** [comment]
暂时不会考虑。或者你也可以自己手动安装这个主题。无非就是下载解压然后在 qBittorrent 的 WebUI 里配置一下而已~
