### ISSUE TITLE
ssh登录问题

### ISSUE THREAD

**Issue by OomelodyoO** [SuLingGG/OpenWrt-Rpi#169]
ssh登录后每隔一段时间自动掉线，再次登录一直失败。
想再次登录成功，需要后台dropbear设置页面点一下保存应用按钮，再登录就成功了。
不知道这是什么情况？

**Comment by SuLingGG** [comment]
有点玄学，我这边无解...
或者你可以按 https://openwrt.cc/restore/ 的方法操作一下，然后重刷一下固件试试。
