### ISSUE TITLE
树莓派4B，请问luci界面可以配置dnsmasq吗？

### ISSUE THREAD

**Issue by KevinxYep** [SuLingGG/OpenWrt-Rpi#171]
安装了最新固件，请问luci界面可以配制dnsmasq吗？网上说还可以通过修改/etc/dnsmasq.conf来实现配置dnsmasq，有没有人好心人可以教我一下，谢谢。

**Comment by Nlqqer** [comment]
@KevinxYep 网络-dhcp/dns

**Comment by SuLingGG** [comment]
把你的 dnsmasq 配置行复制粘贴到 /etc/dnsmasq.conf 末尾就好了，如果这个文件不存在，那你就创建一个文件把这些内容填进去就行。
