### ISSUE TITLE
qBittorrent Web UI 怎么无法登入？

### ISSUE THREAD

**Issue by chan2093** [SuLingGG/OpenWrt-Rpi#173]
新增的qBittorrent功能个人非常感谢。
![image](https://user-images.githubusercontent.com/47651746/125198185-75d69880-e293-11eb-8a17-8c45587686d4.png)
使用了默认root以及password,但无法登入。

**Comment by lxl6125** [comment]
@chan2093 qbittorrent默认用户名：admin，密码：adminadmin

**Comment by chan2093** [comment]
感谢！
