### ISSUE TITLE
ESXI Arm版本支持

### ISSUE THREAD

**Issue by simper** [SuLingGG/OpenWrt-Rpi#179]
有没可能出一个支持 ESXI Arm 上可以虚拟的版本？树莓派 4 已经可以在最新的 ESXI Arm 上成功跑起 windows 11 了，出一个集成各种功能的软路由 openwrt 版本的虚拟镜像是一件很有意思的事情。。。

**Comment by SuLingGG** [comment]
我这边也不知道怎么做这件事...如果可以的话还是用 Docker 跑吧...
