### ISSUE TITLE
希望固件加入ipv6支持

### ISSUE THREAD

**Issue by share18x** [SuLingGG/OpenWrt-Rpi#18]
设备：树莓派2B

**Comment by SuLingGG** [comment]
目前不会考虑，因为树莓派刷 OpenWrt 固件多用于旁路由使用，若在旁路由情况下启用 IPV6，可能会造成 淘宝/支付宝/闲鱼/微博 等 APP 内资源加载缓慢甚至加载失败，严重影响 APP 使用体验。故本系列固件暂时不考虑默认添加 IPV6 支持。
如若确实需要 IPV6，之后我会考虑出一个如何手动启用 IPV6 的教程。

**Comment by share18x** [comment]
好的

**Comment by SuLingGG** [comment]
固件已加入 `ipv6-helper` 工具以实现快速安装 IPV6 依赖并自动配置。详情请参考 [README.md](https://github.com/SuLingGG/OpenWrt-Rpi#启用-ipv6-支持-beta)。并考虑更新到最新版本固件测试体验~
