### ISSUE TITLE
如何安装 luci-app-accesscontrol

### ISSUE THREAD

**Issue by heavenkiller2018** [SuLingGG/OpenWrt-Rpi#180]
在软件包里查找到`luci-app-accesscontrol`, 直接点安装，安装成功后，网络菜单下并没有出现预期的access control功能项，这是什么原因啊？要怎么安装？直接下载了ipk本地安装，也还是在菜单上没显示

**Comment by SuLingGG** [comment]
luci-app-accesscontrol 按理说是默认集成在固件里的，你用的是哪个设备的固件？
