### ISSUE TITLE
更新完无效

### ISSUE THREAD

**Issue by GreenTeodoro839** [SuLingGG/OpenWrt-Rpi#181]
我是树莓派4b，安装更新后版本号没变

**Comment by EnnawYang** [comment]
https://openwrt.cc/restore/  
先把这个刷一遍，再刷一遍新固件  
建议换个好点的内存卡

**Comment by GreenTeodoro839** [comment]
我是80多块买的三星64G内存卡，还需要更好的吗？我在刷完openwrt后扩展了分区到64G左右，和这个有关吗

**Comment by EnnawYang** [comment]
> 我是80多块买的三星64G内存卡，还需要更好的吗？我在刷完openwrt后扩展了分区到64G左右，和这个有关吗

和扩容没关系，不过64有点大，上面的还原镜像可能不适用，建议用电脑慢速格式化一下。这个是使用内存卡的通病，不过使用好的内存卡会好一点，并不是说一定不会发生

**Comment by GreenTeodoro839** [comment]
我在更新固件时选择了保留配置，这有影响吗

**Comment by Supercca** [comment]
我也有同样的问题。下载更新固件升级，选择了保留配置，结果版本号没有更新。

**Comment by GreenTeodoro839** [comment]
> 我也有同样的问题。下载更新固件升级，选择了保留配置，结果版本号没有更新。

我怀疑是系统有问题，我又试了一次，没选保留配置，结果版本号没变，配置还保留了，估计是升级不成功

**Comment by iujmnb98** [comment]
请问有解决办法吗
