### ISSUE TITLE
ssr plus插件

### ISSUE THREAD

**Issue by liuluping0106** [SuLingGG/OpenWrt-Rpi#183]
![捕获](https://user-images.githubusercontent.com/31206648/127467697-01931f5a-4fa2-4dbd-89dc-0d555a8103f3.JPG)
你好，使用最新的树莓派4b版本，但是我自用可以的梯子链接，这里显示是fail，也无法科学上网。求助！

**Comment by dovela** [comment]
时间不对吧，同步下时间

**Comment by liuluping0106** [comment]
已经同步了，还是不work

**Comment by SuLingGG** [comment]
信息有限，我这边无法判断。
