### ISSUE TITLE
nft-qos和网速监控功能不好使

### ISSUE THREAD

**Issue by fallenleavesguy** [SuLingGG/OpenWrt-Rpi#188]
版本: Powered by LuCI Master (git-21.211.30217-03784c3) / ArgonTheme v1.7.2 / OpenWrt R21.7.26 (2021-08-03)

请问ntf-qos无效果以及带宽监控->实时流量监测不准，要怎么解决呢

**Comment by SuLingGG** [comment]
OpenWrt 自带的监控插件都不准，暂时没有什么好的办法。

**Comment by SuLingGG** [comment]
OpenWrt 自带的监控插件都不准，暂时没有什么好的办法。

**Comment by fallenleavesguy** [comment]
我现在用的sirpdboy openwrt, 监控和流控很准，你有需要的话可以看看他们的
