### ISSUE TITLE
gcc编译程序提示没有lpthread

### ISSUE THREAD

**Issue by lwx-bupt** [SuLingGG/OpenWrt-Rpi#19]
就这一个错误
/usr/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
make: *** [makefile:10: all] Error 1

**Comment by SuLingGG** [comment]
你是在什么情况下出现的这个错误？
编译过程中？还是固件使用过程中？

**Comment by lwx-bupt** [comment]
已解决，感谢
