### ISSUE TITLE
无效的用户名和/或密码！请重试。

### ISSUE THREAD

**Issue by googlespeed** [SuLingGG/OpenWrt-Rpi#190]
手动升级了2021 8 6的固件，（从新安装了factory版本）
升级成功之后 导入了之前的配置。配置导入成功，之前设置都生效了，也能通过旧的SSH数据登录，但是web界面一直登录不进去，
提示 无效的用户名和/或密码！请重试。
通过ssh修改密码成功也无法登录。
导入旧的配置之前特意把新的密码修改跟旧的一样。做了几次factory固件，最后只要导入恢复旧的配置文件就不能登录web
https://drive.google.com/file/d/1hMYmkEwXn4oyiN0SQXtAzGZzGRPdmejK/view?usp=sharing

**Comment by sceic** [comment]
确实碰到过这个问题，后来换浏览器登录就好了。

**Comment by SuLingGG** [comment]
尝试清除浏览器 Cookie 再试一下。
