### ISSUE TITLE
树莓派 3B 有加入 passwall 吗?

### ISSUE THREAD

**Issue by touzi** [SuLingGG/OpenWrt-Rpi#2]
希望加入 passwall 功能, 因为这个插件没有独立的 ipk

**Comment by SuLingGG** [comment]
你好~每个版本都是有添加 Passwall 的，每个固件添加了什么软件包可以下载与固件一并提供的 manifest 文件查看，比如树莓派 3B 可以下载 `openwrt-bcm27xx-bcm2710-rpi-3.manifest` 这个文件查看。
![image](https://user-images.githubusercontent.com/22287562/76317208-c6905700-6316-11ea-84c6-bf38086c8c3a.png)

**Comment by touzi** [comment]
找到了, 在 VPN 里面, 请关闭这个主题吧, 谢谢.
