### ISSUE TITLE
树莓派4 板载网卡 无法切换频段，只能在36

### ISSUE THREAD

**Issue by huyu168** [SuLingGG/OpenWrt-Rpi#200]
目前板载网卡不能切换频段，ap模式下只有36能搜索到，并且也不能调整带宽，只能在20mhz，36信道下能搜到信号。这个问题重装了也没有解决

**Comment by huyu168** [comment]
以及，有的时候过几个小时就会自动重启，是温度太高吗？将近60度

**Comment by do21** [comment]
> 以及，有的时候过几个小时就会自动重启，是温度太高吗？将近60度

哈哈哈，我的也会随机重启，但是我加了金属散热器和风扇，温度可以保持在50°上下，超频到2G的话可以在53°左右，推荐上一个。

**Comment by SuLingGG** [comment]
板载网卡只能工作在 AC 和 Legacy 模式下的 20Mhz 频宽，修改频宽是没有作用的，如果无线功能是刚需，还是建议接路由器做 AP 或者买块 USB 无线网卡。树莓派的板载网卡只能说是聊胜于无。
