### ISSUE TITLE
protocol ModemManager not show

### ISSUE THREAD

**Issue by 18rudi** [SuLingGG/OpenWrt-Rpi#204]
protocol ModemManager not show on network interface

**Comment by 18rudi** [comment]
On latest fw didn't show modemmanager on interface

**Comment by SuLingGG** [comment]
It seems that the manifest file included the luci-proto-modemmanager package...

Yesterday I have built a test version, that version was not included luci-proto-modemmanager.

Maybe You should download the latest version then try again. If modemmanager is not shown at the interface page, try add a new interface and select modemmanager proto and try again.

**Comment by 18rudi** [comment]
I have done burn build 2807 but that version was not included luci-proto-modemmanager.
![Screenshot_2021-08-28-14-05-07-918_com android chrome](https://user-images.githubusercontent.com/88720513/131209765-e65f709a-c067-4c68-81aa-f00ab82806a9.jpg)

**Comment by SuLingGG** [comment]
You shoud download the **Latest Version**...
2021-08-27 is the **Test Version** , The latest version is 2021-08-27.
---
![image](https://user-images.githubusercontent.com/22287562/131212839-af763466-79b1-4f35-91ad-dfbb8b785ca3.png)
![image](https://user-images.githubusercontent.com/22287562/131212844-6aaa1e63-113e-48e0-9a5b-2652b4a5bde5.png)
![image](https://user-images.githubusercontent.com/22287562/131212849-00a00e84-ac0d-4785-b85b-497ada2f0c61.png)
![image](https://user-images.githubusercontent.com/22287562/131212853-19bc0ede-b91e-4ae0-9a7e-eca7aa9cde7e.png)

**Comment by 18rudi** [comment]
Where is link latest fw? I download from https://openwrt.cc/releases/targets/bcm27xx/bcm2711/

**Comment by SuLingGG** [comment]
Yes, It's here.

When the latest build job is finished, these files will be replaced to the latest version.

So you can always download firmware files from here.

**Comment by 18rudi** [comment]
thanks for your support
