### ISSUE TITLE
大佬可否添加一下kmod-can

### ISSUE THREAD

**Issue by misakiesl** [SuLingGG/OpenWrt-Rpi#206]

**Comment by SuLingGG** [comment]
opkg update && opkg install kmod-can

**Comment by misakiesl** [comment]
![image](https://user-images.githubusercontent.com/49360253/131243878-70f91247-aff7-484c-b783-b6019e404691.png)
![image](https://user-images.githubusercontent.com/49360253/131243926-5dffa3e2-6df9-43cb-ba80-8dc9efd7d488.png)

我这会出现Unknown package 'kmod-can'.

**Comment by misakiesl** [comment]
> opkg update && opkg install kmod-can

![image](https://user-images.githubusercontent.com/49360253/131245662-69b71e62-cd33-41bc-9992-f86dc8a6394f.png)
![RBW_5HE2MV _1$S504P%F1Z](https://user-images.githubusercontent.com/49360253/131245669-a76f626d-81e2-4f28-a5c4-342748a96ebe.png)
我按您说的这样做和下载下来进行安装都会出现Unknown package 'kmod-can'.这个该怎么办啊

**Comment by SuLingGG** [comment]
现在应该解决了这个问题。下载最新版固件试一下，按如上方法安装 kmod 包就行。

**Comment by misakiesl** [comment]
> 现在应该解决了这个问题。下载最新版固件试一下，按如上方法安装 kmod 包就行。

成功了，谢谢大佬
