### ISSUE TITLE
竞斗云固件大于112M以后opboot不能刷入

### ISSUE THREAD

**Issue by yuanxiang2015** [SuLingGG/OpenWrt-Rpi#208]
OpBoot1.1.0更新日志

修复OpBoot1.0.9无法刷入文件大小超过64M固件的问题，默认最大支持112M大小的刷机文件。
新增支持openwrt，x-wrt, 潘多拉等固件恢复出厂设置。
修复某些体质差的机器概率性无法进入刷机模式的问题。
再次说明一下免得小白又再问，opboot从1.0.9就支持刷潘多拉固件了，不要问我能不能刷了。
opboot从1.0.9之后均不再支持64M分区的固件，有了大分区固件你们还纠结着用小分区是为了什么？难得房子大一点不好么？
还有小白说的opboot不能降级的问题，完全不存在，都说了N次了opboot升级或者降级请使用【opboot-p2w-r619ac-nor-v1.x.x.img】,记住是*.img,不是*.bin。

1.1.2opboot也不能刷入。

**Comment by SuLingGG** [comment]
刚刚移除了 syncthing 和 verysync，明天开始的竞斗云固件体积应该会下降 20+M 左右。

**Comment by celiswen** [comment]
更新之后也不能刷入, 好像你没有写128M之后的都不能刷, 我程序错了?
