### ISSUE TITLE
树莓派4b降速

### ISSUE THREAD

**Issue by yuppieghost** [SuLingGG/OpenWrt-Rpi#210]
用了几天就从300m变50m，什么都没动，都是千m线，重启就恢复了，有可能是什么原因？刷了几个版本都不行

**Comment by SuLingGG** [comment]
你提供的信息量接近为 0，我这儿无法判断。
用 <https://github.com/SuLingGG/OpenWrt-Mini> 然后安装自己需要的软件包试试看吧，如果这种情况仍然出现那说明大概率不是固件问题。

**Comment by yuppieghost** [comment]
关键是我也不知道要提供什么信息。。刚重启都正常

**Comment by SuLingGG** [comment]
我也无能为力...
