### ISSUE TITLE
树莓派刷最新固件，恢复备份，登陆密码失效

### ISSUE THREAD

**Issue by BD4SO** [SuLingGG/OpenWrt-Rpi#218]
我现在的版本是 OpenWrt R21.4.18 (2021-05-26) / LuCI Master (git-21.114.56541-974fb04)  树莓派4B，今天刷了9月12日的固件，从备份文件中恢复设置，能正常运行，但是无法登陆，登陆密码不对。重新刷了好多次还是这样。请问这是什么原因。

**Comment by SuLingGG** [comment]
由于兼容性问题，不建议恢复原来的旧配置。
详见: <https://github.com/coolsnowwolf/lede/issues/7083#issuecomment-864353830>
