### ISSUE TITLE
（openwrt设置）油管视频没法评论

### ISSUE THREAD

**Issue by ZHIMAHOO** [SuLingGG/OpenWrt-Rpi#219]
油管评论的时候显示：Comment failed to post.谷歌了一下意思是开了广告拦截方面的插件所导致。
软路由开了ShadowSocksR Plus+模式是ipRoute。AdGuard Home也是关的。广告拦截这部分设置没有动过，应该是默认的。请问有什么方法可以开启评论。

**Comment by lxl6125** [comment]
@ZHIMAHOO 换个机场试试（换机场，不只是换节点）

**Comment by ZHIMAHOO** [comment]
> @ZHIMAHOO 换个机场试试（换机场，不只是换节点）

还真是这样，我换成版瓦工的机场就好了。看来不是我这边设置的问题，多谢
