### ISSUE TITLE
内存卡被莫名其妙写保护

### ISSUE THREAD

**Issue by huangguiniab** [SuLingGG/OpenWrt-Rpi#221]
我使用的硬件是树莓派4，固件使用的是EXT4分区的版本。因为我的个人原因，每天都要异常断电两三次。这么操作一两天内存卡就会被莫名其妙写保护。我网上搜索后发现，这是EXT4的问题，只要非安全关闭就会被写保护。当然，临时解决问题的方案就是在ssh下运行命令:fsck.ext4 -y /dev/mmcblk0p2。但是这样非常麻烦，而且像我这样子操作，每隔几天就要运行一次。树莓派系统在开机的时候会自动调用fsck来修复EXT4分区来解决写保护这个问题。我在想，openwrt也能不能整这个操作？还有如果我换用squashfs可以彻底解决掉写保护的问题吗？

**Comment by SuLingGG** [comment]
在 https://github.com/SuLingGG/OpenWrt-Rpi/commit/15b7bc489763aa8e7a12a25efb04f9f621128aa9 默认加入了相关配置，可以下载明天的固件试试看。

**Comment by huangguiniab** [comment]
这几天我已经异常断电很多次了，用squashfs很稳定。等会我找张内存卡测试一下ext4行了没有。反正在这几天的使用体验中squashfs异常断电是不会写保护的

**Comment by huangguiniab** [comment]
暂时没有发现问题
