### ISSUE TITLE
我刷了几个R4S的固件，都无法启动。。。

### ISSUE THREAD

**Issue by condywl** [SuLingGG/OpenWrt-Rpi#223]
但是原版的就可以，这是个啥情况。。。

**Comment by SuLingGG** [comment]
按这里的方法试一试。
https://openwrt.cc/restore/

**Comment by condywl** [comment]
好的，谢谢大佬。

**Comment by chenyajunai** [comment]
你换卡就好了，我买到时候店家赠送的说的是C10卡也是启动不了，换了好多固件都不行，我最后自己买的卡说试一下，解决问题了，又刷换固件都好着了
