### ISSUE TITLE
服务->京东签到服务无法登录

### ISSUE THREAD

**Issue by Sicmatr1x** [SuLingGG/OpenWrt-Rpi#225]
IOS手机扫二维码提示：请升级到最新版本的手机京东。但是我的京东APP已经是最新版本了。

**Comment by lxl6125** [comment]
@Sicmatr1x 京东更新了登录模式，扫码获取cookies已经无效了，用浏览器手动获取吧

**Comment by Sicmatr1x** [comment]
> @Sicmatr1x 京东更新了登录模式，扫码获取cookies已经无效了，用浏览器手动获取吧

jd网页的cookie的name是多少

**Comment by Nlqqer** [comment]
@Sicmatr1x 不如把ck给我挂一天几百豆子
