### ISSUE TITLE
树莓派刷openwrt, Docker  页面如何用？

### ISSUE THREAD

**Issue by leechaowen** [SuLingGG/OpenWrt-Rpi#227]
拉取了一个 speedtest 镜像，如何启用它？谢谢指教。这图形化界面 不会了。

https://github.com/librespeed/speedtest

**Comment by zzcabc** [comment]
docker run -d \
    --name speedtest \
    -p 本机端口:80 \
    -e MODE=standalone \
    adolfintel/speedtest


具体看 https://github.com/librespeed/speedtest/blob/master/doc_docker.md
