### ISSUE TITLE
树莓派1b+，i2c无法启用

### ISSUE THREAD

**Issue by Kzs0** [SuLingGG/OpenWrt-Rpi#230]
gpio正常，安装组件报错

opkg install kmod-i2c-gpio-custom_4.14.221-3_arm_arm1176jzf-s_vfp.ipk 

Installing kmod-i2c-gpio-custom (4.14.221-3) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-i2c-gpio-custom:
 *      kernel (= 4.14.221-1-1e1f49421f1facff51a1411021c6d082)
 * opkg_install_cmd: Cannot install package kmod-i2c-gpio-custom.

固件版本 | OpenWrt R20.10.20 / LuCI Master (git-20.256.12360-1a54222)
-- | --
内核版本 | 5.4.75

**Comment by LtD0gE** [comment]
内核版本对不上
找个5.4.75版本的包
