### ISSUE TITLE
能否集成VSSR？

### ISSUE THREAD

**Issue by wangxin6** [SuLingGG/OpenWrt-Rpi#234]
请问能否集成VSSR？谢谢。
https://github.com/jerrykuku/luci-app-vssr

**Comment by zzcabc** [comment]
vssr会与现有的ssr plus冲突，如果你一定要使用vssr ，请先卸载ssr plus ，然后输入opkg update && opkg install luci-app-vssr

**Comment by wangxin6** [comment]
thanks
