### ISSUE TITLE
AdguardHome

### ISSUE THREAD

**Issue by Fregionz** [SuLingGG/OpenWrt-Rpi#235]
Anyone have problem with enabling AdguardHome? it said AdGuardHome RUNNING and Redirected already but my network can't detected in Adguard Log and the DNS not redirected into Adguard. Thank you

Device: Raspberry Pi 4 Model B - openwrt-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz

![image](https://user-images.githubusercontent.com/43022568/135372116-7911f4d8-0863-4501-bdef-64c46cb974c8.png)

**Comment by Feeling1016** [comment]
You have to change your Dns too in Adg. Yours is 5553. Change it to 53.

**Comment by Fregionz** [comment]
The issue solved after i changed on Firewall - Custom Rules, by deleting custom port 53 redirect, i will close this issue, thank yo
![Untitled](https://user-images.githubusercontent.com/43022568/135439656-2d0ef793-f5dd-4781-ace3-244c965184a4.png)
u
