### ISSUE TITLE
竞斗云固件启动不了

### ISSUE THREAD

**Issue by qiangweijian** [SuLingGG/OpenWrt-Rpi#236]
获取不到IP已经很久了  之前老固件都正常

**Comment by 2602575766** [comment]
> 获取不到IP已经很久了 之前老固件都正常

一样的，无线不能获取ip地址，有线获取ip地址慢

**Comment by louisliang723** [comment]
现在最新的有线也无法获取IP地址

**Comment by louisliang723** [comment]
mini的项目里面没有发现bin或者ubi的安装包怎么安装
