### ISSUE TITLE
竞斗云怎么刷mini

### ISSUE THREAD

**Issue by louisliang723** [SuLingGG/OpenWrt-Rpi#242]
在mini的项目的下载地址里面没有发现bin或者ubi的安装包只有以gz和xz结尾的文件不知道怎么安装

**Comment by ligusx** [comment]
https://openwrt.cc/snapshots/targets/ipq40xx/generic/immortalwrt-ipq40xx-generic-hiwifi_c526a-128m-squashfs-nand-factory.ubi
这他喵不是ubi安装包？

**Comment by louisliang723** [comment]
两天前的文件里面没有
