### ISSUE TITLE
树莓派3B，我无论怎么点保存或者应用都不能更改我的配置

### ISSUE THREAD

**Issue by nctqaq** [SuLingGG/OpenWrt-Rpi#247]
![image](https://user-images.githubusercontent.com/63450987/140333637-48181d24-f434-4404-9255-65a33ecd3cc3.png)
![image](https://user-images.githubusercontent.com/63450987/140333762-6a6c6565-813b-446b-89f2-67f3bbdda87d.png)
![image](https://user-images.githubusercontent.com/63450987/140333834-344e7ad7-7823-4338-a5b0-8f98efc50d86.png)
例如SSID，WiFi加密方式和WiFi密码，更改后点击“保存&应用”都会变回OpenWrt和无密码
例如lan接口取消绑定eth0，添加wan口，都不能实现，只会跳回新刷机最初始默认的配置
我只有路由器管理密码更改成功了...

**Comment by nctqaq** [comment]
![image](https://user-images.githubusercontent.com/63450987/140334667-561ce246-2709-42cd-91d6-9a9e39a44ef7.png)
![image](https://user-images.githubusercontent.com/63450987/140334699-6d66b3b8-8a88-40f7-b820-87b793546585.png)

**Comment by nctqaq** [comment]
右上角“未保存的配置”，点保存或者保存&应用，没反应，比如13条未保存，之后还是13条未保存

**Comment by AmadeusGhost** [comment]
显然你的系统只读了，重刷吧。
