### ISSUE TITLE
其他一切正常，为啥mail.qq.com访问不了？

### ISSUE THREAD

**Issue by heavenkiller2018** [SuLingGG/OpenWrt-Rpi#248]
其他一切正常，为啥mail.qq.com访问不了？

显示ERR_CONNECTION_RESET

手机，ipad连上后，google, youtube，instagram访问正常， 但微信连不上，显示“连接中...”, "当前网络不稳定，请检查 你的网络设置"。今日头条能打开，但所有的图片显示不出来（有时候过几分钟后才会显示出来图片）。之前笔记本网络连接那块是会一直显示个球状，“未连上互联网”，但不影响实际上网使用。

感觉是有某一类特殊的网站访问会有问题, 一般是国内的应用， 这是啥原因？是有什么特殊的设置吗？

> 有的说是ipv6设置的原因， 但ipv6设置都取消了，还是一样。

**Comment by rxrw** [comment]
同问，qq.com的所有子域名全访问不了，怀疑是有拦截。。

**Comment by heavenkiller2018** [comment]
> 同问，qq.com的所有子域名全访问不了，怀疑是有拦截。。

你也是碰到同样的问题吗？

**Comment by rxrw** [comment]
> > 同问，qq.com的所有子域名全访问不了，怀疑是有拦截。。
> 
> 你也是碰到同样的问题吗？

对，又出现奇怪的问题了，其他一切正常，lol.qq.com解析到了192.168.0.13，直接访问给我跳转到了红鱼互联网，好奇怪

**Comment by Nlqqer** [comment]
@rxrw 自己检查dns服务

**Comment by rxrw** [comment]
> @rxrw 自己检查dns服务

都是默认配置。开了smartdns openclash做上游

**Comment by heavenkiller2018** [comment]
是啊， 都是默认的一些配置，而且什么样的配置会刚好是qq及头条的一些地址有异常呢？感觉是qq及头条有一些特定的设置和openclash间存在问题

**Comment by Bestlm** [comment]
openclash DNS设置里面打开追加上游DNS试试
