### ISSUE TITLE
固件默认是有超频吗？不知道为什么我的R2S可以跑到1.6Ghz

### ISSUE THREAD

**Issue by roxsky** [SuLingGG/OpenWrt-Rpi#255]
我记得R2S好像是锁频1.2的啊，我这跑到1.6了是不是有问题啊？
![屏幕截图 2021-11-15 230026](https://user-images.githubusercontent.com/4097168/141803948-b1775eb5-9594-4f41-8963-5c4494aeccf9.png)

**Comment by AmadeusGhost** [comment]
上游源码默认就是到 1.6GHz
1.2GHz 你不觉得太低了么...

**Comment by roxsky** [comment]
原来是正常的啊，那就好说了。
我家宽带才100M，1.2Ghz其实都够了，高了我是担心发热，毕竟是被动散热的。
