### ISSUE TITLE
树莓派3B+ 无法保存修改呢

### ISSUE THREAD

**Issue by hyy34** [SuLingGG/OpenWrt-Rpi#26]
无限提示有未保存的设置，例如设置动态 DNS，点启动就无限提示请先保存并应用你的设置。。

**Comment by SuLingGG** [comment]
卡被写只读保护了，建议使用品牌 SD 卡。

可以尝试按图片操作：

![image](https://user-images.githubusercontent.com/22287562/94550691-bb871f00-0286-11eb-833a-e5bc97bf3fdf.png)

或者换卡重试即可解决。
