### ISSUE TITLE
r4s Nps 内网穿透打开不了

### ISSUE THREAD

**Issue by baoeig** [SuLingGG/OpenWrt-Rpi#260]
r4s Nps 内网穿透打开不了

**Comment by baoeig** [comment]
![image](https://user-images.githubusercontent.com/26373492/142571173-897c5d9d-ab7a-42b1-bda8-b5c9ba465b43.png)

**Comment by AmadeusGhost** [comment]
你应该去这里反馈：https://github.com/coolsnowwolf/lede/issues
