### ISSUE TITLE
r4s  ssr不能获取全部节点，这个bug一直存在

### ISSUE THREAD

**Issue by weisuoyuyu** [SuLingGG/OpenWrt-Rpi#261]
r4s  ssr不能获取全部节点，比如有两个香港节点，节点1，节点2，只能获取节点1，这个bug一直存在

**Comment by SuLingGG** [comment]
这是你机场订阅命名的问题，取消所有节点过滤试试。

**Comment by lxl6125** [comment]
这不是应该向ssr那边反馈吗？

**Comment by weisuoyuyu** [comment]
> 这不是应该向ssr那边反馈吗？

我比较小白，我以为是编译导致的。。。。

**Comment by weisuoyuyu** [comment]
> 这是你机场订阅命名的问题，取消所有节点过滤试试。

可能是中文跟数字导致的问题，passwall，小猫咪没有这个问题，我以为编译导致的bug，下面小哥提醒我应该反馈到ssr那里
