### ISSUE TITLE
以前那个300MB左右的固件为什么没了？

### ISSUE THREAD

**Issue by crazygame12345** [SuLingGG/OpenWrt-Rpi#269]
现在所有的固件都变成了openwrt-mini的，以前编译好的内置软件很多的openwrt.img怎么没有了？

**Comment by lxl6125** [comment]
@crazygame12345 需要什么自己安装
https://github.com/SuLingGG/OpenWrt-Mini/blob/main/doc/LuCI-App-List.md

**Comment by crazygame12345** [comment]
> 

请教个问题，新固件里的防火墙里已经没有fullconeNAT的选项了，需要安装什么才能把这个选项找回来

**Comment by SuLingGG** [comment]
> > 
> 
> 请教个问题，新固件里的防火墙里已经没有 fullconeNAT 的选项了，需要安装什么才能把这个选项找回来

Turbo ACC 网络加速 - 全锥形 NAT
