### ISSUE TITLE
mjpg-streamer 已安装但是菜单没发现

### ISSUE THREAD

**Issue by illnino** [SuLingGG/OpenWrt-Rpi#27]
## 问题
软件包搜索‘mjpg-streamer’， 提示已安装
- luci-app-mjpg-streamer
- luci-i18n-mjpg-streamer-zh-cn
- mjpg-streamer

系统 - 启动项 - mjpg-streamer - 已启动

但是服务菜单没找到，同时访问http://192.168.1.40/cgi-bin/luci/admin/services/mjpg-streamer， 也报错。

## 固件版本
OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222)

## 树莓派
3b+

谢谢

**Comment by illnino** [comment]
😂
原来是在网络储存菜单项下。

**Comment by SuLingGG** [comment]
😂😂
