### ISSUE TITLE
WIFI不能无线中继，R4S

### ISSUE THREAD

**Issue by kzh1980** [SuLingGG/OpenWrt-Rpi#275]
不知道用树莓派的同学们，有没有试过用WIFI作为客户端去连上级WIFI，用来实现无线中继？能行吗？
我在R4S下是不能的，但是如果作为Master发射信号，用其他设备去连倒是可以。

 root @ OpenWrt in ~ [17:30:42] 
$ lsusb
**Bus 007 Device 003: ID 0bda:c820 Realtek 802.11ac NIC**
Bus 007 Device 001: ID 1d6b:0002 Linux 5.4.162 xhci-hcd xHCI Host Controller
Bus 002 Device 001: ID 1d6b:0002 Linux 5.4.162 ehci_hcd EHCI Host Controller
Bus 004 Device 001: ID 1d6b:0001 Linux 5.4.162 ohci_hcd Generic Platform OHCI controller
Bus 006 Device 001: ID 1d6b:0003 Linux 5.4.162 xhci-hcd xHCI Host Controller
Bus 008 Device 001: ID 1d6b:0003 Linux 5.4.162 xhci-hcd xHCI Host Controller
**Bus 005 Device 002: ID 0bda:c820 Realtek 802.11ac NIC**
Bus 001 Device 001: ID 1d6b:0002 Linux 5.4.162 ehci_hcd EHCI Host Controller
Bus 003 Device 001: ID 1d6b:0001 Linux 5.4.162 ohci_hcd Generic Platform OHCI controller
Bus 005 Device 001: ID 1d6b:0002 Linux 5.4.162 xhci-hcd xHCI Host Controller

我本来插了两个设备，想要一个连上级WIFI，另一个作为无线AP，中间挂SSRP的。但是发现作为Client连上级WIFI连不了。

为了解决这个问题，把R4S各路神仙的第三方固件都刷了一遍，哈哈。发现就无线驱动来说，还是 SuLingGG/immortalwrt 和DHDAXCW 支持得比较好。但是两个固件都遇到了同样的问题，不知何故？

搜索资料过程中，有网友说要设置国家代码为RU，模式为AC，信道149，频段80M的，重启生效的，等等。大概全都搞了一遍。貌似还是不行。

**Comment by AmadeusGhost** [comment]
不要把我们的项目跟抄袭者的相提并论，还有你这种用法只有硬路由才支持。
