### ISSUE TITLE
能否为树莓派4B添加koolproxyR plus去广告插件呢？

### ISSUE THREAD

**Issue by immyonlystar** [SuLingGG/OpenWrt-Rpi#30]
作者你好。看固件说明，树莓派固件去广告插件有koolproxyR plus，但我下载了最新的树莓派4B固件，刷机后发现并无此插件，能否添加呢？

**Comment by SuLingGG** [comment]
koolproxyR plus 因为之前有一些未知问题，无法在 OpenWrt 上运行，所以不再支持。
