### ISSUE TITLE
树莓派 3B/3B+ 的基于lean大的镜像中syncthing启动失败

### ISSUE THREAD

**Issue by cqiyu** [SuLingGG/OpenWrt-Rpi#31]
[镜像](https://github.com/SuLingGG/OpenWrt-Rpi/actions?query=workflow%3A%22Build+Raspberry+Pi+3+Lean%27s+OpenWrt%22)
树莓派 3B/3B+ 的基于lean大的镜像中syncthing启动失败

**Comment by cqiyu** [comment]
最近几次的镜像，包括squashfs-sysupgrade，squashfs-factory，ext4-sysupgrade，ext4-factory，都有刷过，刷都有试过启动syncthing，但是几秒后状态就变成“未启动”，然后再次无法启动

**Comment by SuLingGG** [comment]
多谢反馈，这个问题应该是上游源码的原因，即可能在 syncthing 1.9.0 以下的版本中存在。据说 1.9.0 已经修复了这个问题，晚些时间我 bump 一下包的版本试试看~

**Comment by SuLingGG** [comment]
从今天的固件开始，此问题已解决:
![Snipaste_2020-10-29_17-00-27](https://user-images.githubusercontent.com/22287562/97547524-de812c00-1a08-11eb-9066-34bbab3f5702.png)

**Comment by cqiyu** [comment]
万分感谢作者，作者辛苦啦
