### ISSUE TITLE
能不能出一款精简版

### ISSUE THREAD

**Issue by Omoinemie** [SuLingGG/OpenWrt-Rpi#32]
整合版东西太多了，挺占内存，出一款精简版，只保留不能从软件包仓库下载的插件，能在线下载的可以自己按需安装。如果条件允许的话，可自建第三方插件包IPK仓库。

**Comment by SuLingGG** [comment]
已经有不下 20 个人提出相似的建议了，我的回复一直都是:

**「精简版固件当前不会考虑，以后也没有出精简版的打算」**

1. 固件大小问题: 默认设定 960M 的 RootFS 是为了给喜欢折腾的人留出比较充足的折腾空间，SD 卡大小现在都 16G 起步了，所以固件大小不成问题，如果 RootFS 占用的空间不够用，我也有提供扩容教程。

2. 内存占用问题: 固件日常运行所占 RAM 大小在 300M 以下，虽然插件多，但开机默认运行的插件并不多。即使是树莓派 1 也可以流畅运行。

3. 软件仓库的问题，项目提供 package-server.zip 文件，有兴趣的话可以研究下怎么用。

4. 关于 Luci 界面插件太多/不好找/强迫症的问题: 这也是最重要的一个原因，精简版固件固然专治强迫症，但是不同人的需求是不一样的，你用 frp，他用 clash，他用 kms，出精简版固件最后的结局不外乎又收到“可不可以给精简版加 xx 功能”的反馈，如果像这样先做减法后做加法我个人觉得意义不大。另外又不是 24 小时呆在 Luci 界面的，刷好固件一次配置完 Luci 就可以扔那儿不管了，所以强迫症这些 Duck 不必...

如果你确实需要专属自己的精简定制版固件，可以 Fork 此项目通过 Github Action 自行编译。
