### ISSUE TITLE
可否在action里加入docker推送

### ISSUE THREAD

**Issue by a-little-cat** [SuLingGG/OpenWrt-Rpi#38]
您好,我的部署环境是在esxi上开ubuntu,在ubuntu的docker里启动openwrt;
由于物理机是x86环境,因此性能,空间都不是瓶颈,而且回滚更新都非常方便,重启只需几秒;

在这个过程中,我总是手动下载最新的docker镜像,手动导入;
请问是否考虑在github action里,添加推送到docker hub功能,这样配合docker的自动更新,可以全自动化部署

**Comment by SuLingGG** [comment]
请移步:
https://github.com/SuLingGG/OpenWrt-Rpi-Docker

**Comment by a-little-cat** [comment]
感动 拜谢
