### ISSUE TITLE
树莓派4B，ADBYBY为何一直显示未运行

### ISSUE THREAD

**Issue by q405812306** [SuLingGG/OpenWrt-Rpi#4]
L大说是64位无法运行，那应该怎么做才能运行呢。。。谢谢了

**Comment by SuLingGG** [comment]
如果刚需 ADBYBY，建议刷入树莓派 2B 的 32 位固件。
树莓派 4B 刷入 32 位固件后，需要使用网线连接树莓派和电脑，在 “接口 - 无线” 中将无线模式、信道、频宽调为如图所示即可使用。
![image](https://user-images.githubusercontent.com/22287562/76771218-f8ebf980-67d9-11ea-942a-e33d2c082b36.png)

**Comment by q405812306** [comment]
好的
