### ISSUE TITLE
请问有没有办法关闭shadowsocksr遍历节点测速？

### ISSUE THREAD

**Issue by vkboo** [SuLingGG/OpenWrt-Rpi#40]
点击“服务”- “ShadowSocksR Plus+” - “服务器节点”总是会遍历订阅的节点测速，因为自己的机场有规定，频繁的全节点测速可能会被封号，所以想关闭这个功能，所以想问问能不能关闭测速功能？
还有，除了上面提到的主动触发测速之外，服务本身会在后台自动测速（比如2点订阅节点的时候）吗？

**Comment by SuLingGG** [comment]
最简单的方法是使用 passwall，有开启和关闭 "自动测速" 的选项。即使关闭也可以手动测速。
另外不管是 ShadowsocksR Plus+ 还是 Passwall，都只会在用户进入节点列表里面的时候才会触发测速，在后台不会自动测速的。
另外说句题外话，用户测不测速是用户的自由，这种喂用户吃屎的辣鸡机场不用也罢。

**Comment by vkboo** [comment]
@SuLingGG 感谢！♥
