### ISSUE TITLE
mwan3

### ISSUE THREAD

**Issue by sklohk** [SuLingGG/OpenWrt-Rpi#45]
日常需要使用mwan3，试着安装，安装不了:
依赖的软件包 iptables-mod-conntrack-extra 在所有仓库都未提供。
依赖的软件包 iptables-mod-ipopt 在所有仓库都未提供。
可否处理？谢谢

**Comment by SuLingGG** [comment]
已于 https://github.com/SuLingGG/OpenWrt-Rpi/commit/631967e3e0e2ab9ebf8288a8f3c542db7caa55d4 添加，明日固件生效。

**Comment by sklohk** [comment]
谢谢。
这几天一直在尝试，因为刚刚接触树莓派，在此之前是在vmware上跑openwrt，还是有很大的不同，我也尝试了Docker 镜像，但Docker
镜像里没有存内核模块，一安装软件包几乎都有内核兼容问题，我也在用4G的模块尝试，特别是华为的，我手头是me909s，宿主机可以识别，但openwrt
里就不行了，非Docker的镜像也不能，下午把杭州Mcuzone提供的USB-mode. json搬过去，就可以了，加上其提供的script,
me909s，就可以上线了。我还买了个移远，高通芯片的，等到了再试试。
谢谢你的快速回应。

sk

SuLingGG <notifications@github.com> 于 2020年11月15日周日 下午2:23写道：
