### ISSUE TITLE
Music Remote Center - no sound

### ISSUE THREAD

**Issue by truefriend-cz** [SuLingGG/OpenWrt-Rpi#47]
Hi. I am found a bug...

If Enabling Music Remote Center and play music then not a sound to 3,5mm headphone jack.

How i can solving this?

Device: RPi 4B, OS: Lean (2020-11-15)

**Comment by SuLingGG** [comment]
Try:

```
echo "dtparam=i2c_arm=on,audio=on" >> /boot/config.txt
```

Then reboot.

**Comment by truefriend-cz** [comment]
Thnak you very much!! You are gold! :)
And, bonus..., do you know any app for Bluetooth management (on your builds)?
