### ISSUE TITLE
请问如何挂载烧录后的未使用空间？

### ISSUE THREAD

**Issue by nakamakaede** [SuLingGG/OpenWrt-Rpi#49]
请问如何挂载烧录后的未使用空间？
谢谢

**Comment by SuLingGG** [comment]
如果你想利用空闲空间新建分区，可以通过在“系统 - 磁盘管理” 中在空闲空间上新建一个 ext4 分区，并且在 “系统 - 挂载点” 中启用挂载这个分区。
如果你想将根目录扩容，请参考文档:
<https://mlapp.cn/1011.html>

**Comment by nakamakaede** [comment]
明白了，谢谢
