### ISSUE TITLE
Wireguard 在哪里配置？

### ISSUE THREAD

**Issue by bao3** [SuLingGG/OpenWrt-Rpi#5]
我想使用 wireguard 功能，也发现在状态显示里面有 ‘wireguard状态' 但是我在下面的 vpn 设置里面没有找到，VPN 的设置几乎都是 SSR/VMESS/IPSec/OpenVPN 等等。
我该在哪里找到 wireguard 的设置。

**Comment by SuLingGG** [comment]
请前往:
"网络 - 接口 - 添加新接口"
配置 WireGuardVPN~

**Comment by bao3** [comment]
@SuLingGG  感谢解答，找到了。

Closed
