### ISSUE TITLE
你好 请问树莓派外接usb3.0无线网卡，速度被限制在100M，应该怎么解决？

### ISSUE THREAD

**Issue by nakamakaede** [SuLingGG/OpenWrt-Rpi#55]
用的树莓派4b，外接网卡是网件A6210，最近发现连接5GHz WIFI 时，速度被限制在了100M （国内国外测速都是一样）
本地带宽200M，布线和WIFI均支持千兆网络，不知道速度瓶颈是在哪里

**Comment by nakamakaede** [comment]
我将网卡换到树莓派上面的USB3.0网口之后，发现速率突破100M了，基本算解决了问题
请问上下两个usb3.0接口是有什么区别吗，是供电不足还是什么原因？

**Comment by SuLingGG** [comment]
好像电路设计上，挨板载网口偏上的 USB 口体质更好一些，另外不建议插延长线使用网卡，可能会带来奇奇怪怪的问题。

**Comment by nakamakaede** [comment]
好的，谢谢您了
