### ISSUE TITLE
树莓派4B openclash用不了

### ISSUE THREAD

**Issue by itnewgay** [SuLingGG/OpenWrt-Rpi#56]
刷了不同的版本。 但是OPENCLASH总是无法开启。一直提示开启失败。内核版本一直显示未知。
![image](https://user-images.githubusercontent.com/43598975/100736677-14517000-340e-11eb-8b03-555f533e446f.png)
但是点更新，又会说更新成功。

OpenClash 调试日志

生成时间: 2020-12-01 19:56:59
插件版本: v0.41.05-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: Raspberry Pi 4 Model B Rev 1.2
固件版本: OpenWrt SNAPSHOT r0-8cf4d9a
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 5.4.79
处理器架构: aarch64_cortex-a72

#此项在使用Tun模式时应为ACCEPT
防火墙转发: REJECT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.11.23.g4474306
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-232-ge389e33
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/175501.yaml
启动配置文件: /etc/openclash/175501.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

**Comment by SuLingGG** [comment]
首先这不是固件的问题，我的项目确实已经在编译时内置了 Clash 核心，但是核心是通过 OpenClash 项目内下载的:

https://github.com/vernesong/OpenClash/releases/tag/Clash

并且下载的核心也是 OpenClash 开发者经过压缩后的核心 (占用更小 ROM 空间)。

但是经过我的测试，此版 OpenClash 项目内提供的核心在树莓派 4B 上有一些问题，具体表现为在执行二进制文件时，会抛出错误：

`Illegal instruction`

因为在 OpenClash 的 LuCI 里更新内核还是会下载 OpenClash 项目内的内核 (换句话说下载的还是是同一文件)，所以在 OpenClash 的 LuCI 里更新内核并不能解决实质性的问题。

此时可以通过替换 Clash 核心为官方 Clash 项目下未压缩的核心来解决：

进入树莓派 OpenWrt 的 SSH 或者 TTYD 终端，依次逐行执行以下命令即可:

```
cd /etc/openclash/core
rm -rf clash
wget -qO- https://github.com/Dreamacro/clash/releases/download/v1.3.0/clash-linux-armv8-v1.3.0.gz | gunzip -c > clash
chmod +x clash
```

建议在执行以上命令的时候先用 SSR++ 或者 Passwall 在 OpenWrt 上挂一层梯子，然后再执行以上命令；

或者把文件下载到本地，命名为 `clash` 后上传到 `/etc/openclash/core` 目录，最后 chmod +x 赋予可执行权限即可。

**Comment by itnewgay** [comment]
感谢回复. 我又单独下载了clash 1.2放上去.可以用了.
