### ISSUE TITLE
集成 udptools ，设置 udpspeeder & udp2raw

### ISSUE THREAD

**Issue by bao3** [SuLingGG/OpenWrt-Rpi#6]
我刚刚自己在 git clone https://github.com/atrandys/luci-udptools  这个 repo 想手动安装上 udpspeeder , udp2raw 以及  luci-udptools 。

但是我想，目前使用这个方案加速越来越多，能不能在自动编译时就集成？

**Comment by SuLingGG** [comment]
可能会在一周内测试一下，没问题的话会加上~

**Comment by bao3** [comment]
> 可能会在一周内测试一下，没问题的话会加上~
> 这几天可能会有些忙，进度要开始放缓了...

感谢回应。我在前天晚上，Fork 三个不同的源，修改了一下，已经测试过可以很好运行。所以可以直接使用 
https://github.com/bao3/openwrt-udp2raw
https://github.com/bao3/openwrt-udpspeeder
https://github.com/bao3/luci-udptools

**Comment by SuLingGG** [comment]
已按您的项目地址添加了这三个包，欢迎测试~

**Comment by bao3** [comment]
谢谢，我今晚编译看看。太感谢了。
