### ISSUE TITLE
ping经常有毛刺和抖动，cpu会突然high几秒，netdata里看到也一样，如何抓出元凶？

### ISSUE THREAD

**Issue by galaxyskyknight** [SuLingGG/OpenWrt-Rpi#63]
从设备ping软路由，不管有线还是无线，总是偶尔会出现delta high cpu,导致ping lag很高，netdata里看到eth0-eth5有断流。softirq很高，top下看不出来哪个进程是罪魁，服务里停了一堆服务逐个排查，无果，还是一样，请问有什么办法抓出来是什么原因？

![image](https://user-images.githubusercontent.com/66289873/102907115-84ed2900-44b0-11eb-83d8-5e24e2e44bd9.png)

**Comment by SuLingGG** [comment]
技术有限，无法排查...
另外推荐把树莓派作为旁路由使用，看你的 IP 地址应该是做主路由了。

**Comment by galaxyskyknight** [comment]
已经排查出来了，请关闭，是wpad这个服务干扰网卡，无线认证的这个包有毒，网口高负载时，会产生大量软中断，具体与wpad这个包的祸害关系位置，可能是驱动层面的。反正停止禁用这个后消停了。。

**Comment by InsOnYou** [comment]
> 技术有限，无法排查...
> 另外推荐把树莓派作为旁路由使用，看你的 IP 地址应该是做主路由了。

树莓派作为主路由有什么缺点吗？
