### ISSUE TITLE
无法更新 xray和v2ray

### ISSUE THREAD

**Issue by 6668412** [SuLingGG/OpenWrt-Rpi#64]
更新xray时报错:
您没有填写 Xray 路径。请保存应用后再手动更新。
但下面有默认路径   （重新复制粘贴一下路径，已解决，可能是个小bug？）
更新v2ray时报错:
无法移动新文件到：/usr/bin/v2ray/

**Comment by SuLingGG** [comment]
我这儿好像没有这个问题...
![Snipaste_2020-12-23_17-31-29](https://user-images.githubusercontent.com/22287562/102982096-f7a7e400-4544-11eb-9b09-1750272c0cf4.png)
![Snipaste_2020-12-23_17-32-24](https://user-images.githubusercontent.com/22287562/102982105-fb3b6b00-4544-11eb-86b9-9dbae99ac0c2.png)
![Snipaste_2020-12-23_17-32-33](https://user-images.githubusercontent.com/22287562/102982112-fd9dc500-4544-11eb-8360-88f269729539.png)

**Comment by 6668412** [comment]
我重新下载并安装了固件，但是还是出现这个问题，并且又发现无法保存更改的配置（右上角提示）
![Screenshot 2020-12-23 202717](https://user-images.githubusercontent.com/75165009/102996112-71e46280-455d-11eb-94d5-b3e32c2a3e8b.png)

**Comment by 6668412** [comment]
![image](https://user-images.githubusercontent.com/75165009/102996231-af48f000-455d-11eb-8468-90c226eb8a26.png)

**Comment by SuLingGG** [comment]
先把这个文件刷入 SD 卡，无需插卡开机，紧接着再刷入我的固件试一试。
[Restore-SDCard-2G.img.zip](https://github.com/SuLingGG/OpenWrt-Rpi/files/5735129/Restore-SDCard-2G.img.zip)

**Comment by 6668412** [comment]
我试了一下，固件更新貌似好了，但是不能保存配置的问题还在
![dsfsadsa](https://user-images.githubusercontent.com/75165009/103002621-2dab8f00-456a-11eb-8b65-5880c11d0697.png)

**Comment by SuLingGG** [comment]
那说明你这张 SD 卡生命快走到尽头了，换张卡吧...

**Comment by 6668412** [comment]
哈哈，谢谢了，我会为这张卡寻找一个合适的归宿的^^
