### ISSUE TITLE
新版R2S端口转发失效

### ISSUE THREAD

**Issue by czw1259** [SuLingGG/OpenWrt-Rpi#65]
家里黑群晖外网无法连接，设置了端口转发连接不了啊！拜托修复下！！谢谢

**Comment by SuLingGG** [comment]
我没有做与防火墙相关的修改，你可以先用一下其他人的固件，如果其他人的固件也有这个问题的话，建议带上详细日志和问题复现情况至 <https://github.com/coolsnowwolf/lede> 提 Issues，这样一句话的描述其实和 "我的电脑上不了网，怎么办" 一样，没人能定位到问题出在哪儿。
