### ISSUE TITLE
希望能加入rtl8811cu和rtl8812bu的驱动

### ISSUE THREAD

**Issue by rangerwill** [SuLingGG/OpenWrt-Rpi#66]
希望能加入rtl8811cu和rtl8812bu的驱动
毕竟这两款网卡的存世量是很大的
谢谢大佬！

**Comment by SuLingGG** [comment]
现在能加的驱动都加上了...如果不能用那就说明不支持。另外 OpenWrt 对螃蟹卡的支持并不好，所以非常不建议买螃蟹卡。详情请参阅 “网卡支持与推荐”。
