### ISSUE TITLE
[建议/RPi] 未来是否考虑加入CPU温度显示？

### ISSUE THREAD

**Issue by galendai** [SuLingGG/OpenWrt-Rpi#70]
感谢SuLingGG的固件非常好用。未来是否可以考虑在树莓派固件中加入温度显示？或有文档能指点一下如何自行设置？感谢！

**Comment by SuLingGG** [comment]
现在的固件应该有温度显示的吧？
在概览界面，即登陆控制面板的第一个界面。

**Comment by galendai** [comment]
目前仅显示CPU使用率， 固件版本5.4.91
![image](https://user-images.githubusercontent.com/2900743/105851816-89ac7c00-601e-11eb-84da-5882fc11d821.png)

**Comment by SuLingGG** [comment]
ARMv8 Processor x 4 (1400Mhz, **55.8℃**)
这里面的 **55.8℃**
不是 CPU 温度吗...

**Comment by SuLingGG** [comment]
ARMv8 Processor x 4 (1400Mhz, **55.8℃**)
这里面的 **55.8℃**
不是 CPU 温度吗...

**Comment by galendai** [comment]
抱歉，眼花了。如果能拆出来单独显示更好。issue close for now.

**Comment by SuLingGG** [comment]
> 抱歉，眼花了。如果能拆出来单独显示更好。issue close for now.

这里的显示布局是源码规定的，我基本上也是本着能不改就不改的原则，其实是懒 (
