### ISSUE TITLE
请问大佬，为什么端口转发不了呀。。。

### ISSUE THREAD

**Issue by alicechino** [SuLingGG/OpenWrt-Rpi#72]
WAN的入站都已经改成接受了...还是不行
转发内部端口到WAN口上，访问不了..

**Comment by alicechino** [comment]
我这边是公网ip...以前用KS的LEDE一直正常转发，换这个一样设置好但是怎么都转发不出去..

**Comment by alicechino** [comment]
更新一下问题...实测下来似乎是，我如果是用软路由的网络访问，不论是公网IP+端口还是我DDNS之后的网址+端口都不能访问NAS，比如我手机开4G或者5G都可以访问，但是一旦连WIFI切回内网就不行了。。这要怎么设置才行呢？

**Comment by alicechino** [comment]
解决了 要做NAT回流，或者在主机名那直接输入DDNS之后的网址就行

**Comment by moshouhot** [comment]
这个固件NAT回流有BUG，其实是docker的锅，我的方法是给内网不同设备分配不同的二级域名，然后在主机名里设置域名对应的内网IP.
