### ISSUE TITLE
SSRP 用trojan-go添加结点起不来

### ISSUE THREAD

**Issue by galaxyskyknight** [SuLingGG/OpenWrt-Rpi#74]
具体见https://github.com/coolsnowwolf/lede/issues/6305
不知道是lede原版还是你这块编译的问题。

**Comment by AmadeusGhost** [comment]
你应该去源码地址发 issue 而不是这里。

**Comment by Elletear** [comment]
😂去[ssrp](https://github.com/fw876/helloworld)源码处发比较好
