### ISSUE TITLE
树莓派 Wi-Fi 配置WPA2-PSK/WPA3-SAE混合模式 无法连接

### ISSUE THREAD

**Issue by hmsjy2017** [SuLingGG/OpenWrt-Rpi#77]
出于安全性的需要，还是设置了密码。
设置WPA2-PSK/WPA3-SAE混合模式，无法连接Wi-Fi，设置WPA2-PSK，可以正常连接。
（测试设备：iPad ）

**Comment by SuLingGG** [comment]
这个问题我这边无法解决。暂时还是用 WPA2 吧。

**Comment by hmsjy2017** [comment]
OK
