### ISSUE TITLE
如何自定义编译固件

### ISSUE THREAD

**Issue by hmsjy2017** [SuLingGG/OpenWrt-Rpi#80]
我用的一直是 Raspberry Pi 4 Lean's OpenWrt 固件，可能是我用过功能最全的固件（虽然我很多都不会用。。）
由于很容易弄坏系统，重装之后再配置比较耗时，所以想预先配置完，做到开箱即用。
希望预先配置的包括但不限于：
- root 用户名及密码
- Luci 管理地址
- WiFi 模式
- WiFi 工作频率（2.4GHz/5GHz）
- WiFi 信道（11/Auto）
- WiFi 密码及加密方式（WPA2-PSK/None）
- LAN 口：
  + 协议：静态地址
  + 网关
  + 广播
  + DNS 地址
  + 打钩：忽略此接口/不在此接口提供 DHCP 服务 
- 启用 IPv6 支持
- 预配置 OpenClash 订阅/配置文件

**Comment by leungzw** [comment]
自带备份功能

**Comment by SuLingGG** [comment]
建议使用 “系统 - 备份/升级” 功能导出设置好 OpenWrt 的固件配置文件归档文件，刷入或者还原固件后，导入此归档文件即可将 OpenWrt 配置还原至备份时的状态。

目前固件不支持通过 sysupgrade 文件升级。

如果你是通过重刷 factory 文件来升级的，通过此种方法导入配置有一定概率出现不兼容的情况。

但导入同一天编译的固件的归档文件应该不存在这个问题。
