### ISSUE TITLE
为什么x86找不到factory版本?

### ISSUE THREAD

**Issue by cxfksword** [SuLingGG/OpenWrt-Rpi#81]
我想全新安装到硬盘，但找不到factory版本，直接升级会提示分区出错

**Comment by SuLingGG** [comment]
x86 平台的固件是安装/升级一体固件。

https://mlapp.cn/1004.html#x86-%E5%B9%B3%E5%8F%B0

如果你要将固件写入到实体机硬盘，建议先用 U 盘内的 PE 启动，然后再用 Etcher 将固件写入到硬盘试试。

由于兼容原因某些工具确实无法将此项目固件写入到硬盘，这个原因我无法排查，但是我这边是没有问题的。

如果 Etcher 看不到本地硬盘，请到处点点，多琢磨琢磨。

如果你的 PE 无法运行 Etcher，请尝试用 edgeless 或者 firpe 这两款 PE 试试。

实在不行就跑个 Linux LiveCD 把固件 dd 进硬盘吧。

**Comment by cxfksword** [comment]
多谢回复，最后是用Etcher写入成功了，之前试过physdiskwrite，diskimage 都是最后剩 20 字节出错😂

**Comment by SuLingGG** [comment]
最后成功了就行~
