### ISSUE TITLE
TTYD 终端空白

### ISSUE THREAD

**Issue by hmsjy2017** [SuLingGG/OpenWrt-Rpi#82]
![A59DD8A5-8E3D-460A-A4A3-35271E80DADF](https://user-images.githubusercontent.com/42692274/107200261-72b05580-6a32-11eb-8e3a-1aba33431971.png)

**Comment by SuLingGG** [comment]
如果你刷完固件没有重启过，这是正常的。

可以尝试：

```
/etc/init.d/ttyd restart
```

或者：

![image](https://user-images.githubusercontent.com/22287562/107201802-704efb00-6a34-11eb-9ea7-c80643425937.png)

或者直接重启 OpenWrt 可解。
