### ISSUE TITLE
r2s在线升级固件，固件版本号不变正常吗？

### ISSUE THREAD

**Issue by hhxuke** [SuLingGG/OpenWrt-Rpi#89]

**Comment by SuLingGG** [comment]
最近此项目的固件升级功能好像有一些问题，无法升级成功。
上传固件升级之后相当于手动重启一次，不会升级成功。但是对系统也没有什么影响。
如果想升级固件的话还是建议重新刷入固件。

**Comment by L1cardo** [comment]
这个问题修复了吗

**Comment by SuLingGG** [comment]
> 这个问题修复了吗

这是上游的原因。
我这边暂时没有办法修复。
