### ISSUE TITLE
想在R2S上继续用之前2550的系统，但是按照教程弄到Actions之后死活不开始编译，https://github.com/aoxueos/ZeroProject_TestOpenWrt/actions/workflows/r2s_home.yml，万分感谢，方便的话帮我看下，我会尽力的，谢谢

### ISSUE THREAD

**Issue by aoxueos** [SuLingGG/OpenWrt-Rpi#90]

**Comment by NekokeCore** [comment]
https://github.com/aoxueos/ZeroProject_TestOpenWrt/blob/7926e813a4f7d76e3a4513951909725ff452bfa9/.github/workflows/r2s_home.yml#L14

试试把    if: github.repository == 'klever1988/nanopi-openwrt'
改为 github.event.repository.owner.id == github.event.sender.id
