### ISSUE TITLE
树莓派2，添加wan口后lan口设备无法上网，openwrt本身可以上网。

### ISSUE THREAD

**Issue by dos7lo** [SuLingGG/OpenWrt-Rpi#91]
这个问题比较奇怪，我是树莓派2+usb网卡，网卡可以正常识别。此前正常使用过一段时间，后来刷新版出现问题，无法上网，就放弃了一阵子。
最近刷新版想看看有没有解决，操作上**只有修改lan口ip地址，添加wan口（DHCP模式，使用USB网卡）**，但无法上网，而**使用mini版同样操作，可正常上网**。

非mini版的树莓派 openwrt**本身可以上网**，可以ping通互联网上的ip，可以ping通网关，但ping不通openwrt通过dhcp分配的ip，然后这个ip 的主机可以ping通openwrt，但ping不通网关，也无法上网。

**Comment by SuLingGG** [comment]
我这边也无解...
建议手动设置一下树莓派 Lan 口的网关和 DNS 都为树莓派的 Lan 口 IP。
然后检查一下树莓派 Lan 口和 Wan 口的防火墙区域设置是否正确。
![image](https://user-images.githubusercontent.com/22287562/109146163-6b14de80-779e-11eb-87c1-8f1fe9afccbe.png)
