### ISSUE TITLE
动态DNS里的配置要如何增加？

### ISSUE THREAD

**Issue by caibok80** [SuLingGG/OpenWrt-Rpi#92]
能否下回更新时集成配置选项。

**Comment by SuLingGG** [comment]
我不知道你要表达什么内容...
动态 DNS 里已经集成了几十种 DNS 服务提供商。
之前有反馈说 Offical 版 OpenWrt 可能会出现 DNS 服务提供商空白的问题，如果你用的是 Offical 版那么请换回 Lean 版试试。
