### ISSUE TITLE
R2S非beta版本 重启必定故障

### ISSUE THREAD

**Issue by EEEricZer** [SuLingGG/OpenWrt-Rpi#93]
使用的是淘宝上的成品r2s（20年12月），增加了一个usb转千兆网口。
![图片](https://user-images.githubusercontent.com/50194098/109254088-41a29400-782c-11eb-8e24-da6f19529b56.png)
奈何卖家说不清具体网卡型号，r2s似乎现在卖的多的都是双网口的了，想着大差不差，网上找到了[这张图](https://pic3.zhimg.com/80/v2-a7e974b300922b56859ed19bb1eff4ca_720w.jpg)也许应该可能（？）提供了比较详细的配置参数。

R2S 尝试了结束beta版本之后的几个固件，都有如下问题：
1. 使用 `reboot`命令重启/系统点击“重启”进行重启/定时重启，开机后一定会出现wan口无法使用（接口灯不亮）；
2. 在1的情况中，软路由的dhcp功能也无法正常使用，Windows的IP地址为169.254.173.152；
3. 在2情况中，指定192.168.1.xx地址后，也无法进入软路由界面；
4. 强行重新插拔电源，有可能恢复正常（大概率）/继续维持1情况（小概率）/LAN口灯也熄灭（中概率）。
5. 使用[其他](https://github.com/klever1988/nanopi-openwrt)固件（使用的配置与应用几乎相同），以上问题全部消失。

**Comment by SuLingGG** [comment]
我这里也没啥头绪，但是因为你说的这个固件所用的源码 (FriendlyWrt) 与我固件所用源码 (Lean 版 OpenWrt) 不相同，所以我这边也确定问题出在哪里...
或者你可以按这里的方法试试看:

<https://openwrt.cc/restore/>

如果还是不行我这边也没有什么好的办法了。
