### ISSUE TITLE
树莓派2B 无法使用USB无线网卡.

### ISSUE THREAD

**Issue by lewisxhe** [SuLingGG/OpenWrt-Rpi#94]
已经排除无线网卡故障，使用原版Openwrt 可以正常启用 工作正常，使用`OpenWrt SNAPSHOT r0-8d8125a / LuCI openwrt-19.07 branch git-21.050.37945-c33df8f`  无法开启，显示如下图
![0210227114013](https://user-images.githubusercontent.com/22990954/109374528-f605ee00-78f0-11eb-8829-1774bca624ec.png)

**Comment by SuLingGG** [comment]
我的文档里说了，有一些驱动即使已在固件中集成可能也无法正常工作。
还有一种情况是这些驱动无法被 Luci 控制，这些网卡一般为“螃蟹卡”即网卡芯片型号为 RTL 开头的无线网卡。
我还是建议买一块网件 A6210，闲鱼 100 块以下就能搞定。兼容性非常好。

**Comment by lewisxhe** [comment]
OK ! 收到 。我没反应过来 ！😂
