### ISSUE TITLE
能否与官版稳定版同步确认一个稳定版，加以标注？

### ISSUE THREAD

**Issue by AxIauk** [SuLingGG/OpenWrt-Rpi#95]
感谢非常有用，好用。
能否与官版稳定版同步确认一个稳定版，加以标注？

**Comment by SuLingGG** [comment]
应该不会考虑。

首先“稳定版”是否“稳定”以及“何为稳定”本身需要商榷的问题。

如果要推出“稳定版”，我需要在每个设备上测试一下某个版本的固件。

一来，我没有树莓派 1/2B/R2S/R4S/x86_generic 这些设备；
二来，即使是我手中有这些设备，我也没有那么多时间和精力；
三来，即使推出了稳定版，我也不能保证此版固件在每个人的配置基础上都能工作稳定。

所以我个人认为“稳定版”是噱头大于实际的一个东西。我个人也推荐:
**“没有问题就不要更新”**

所以自己用着稳定的版本就是“稳定版”。
如果每个版本你都觉得“稳定”，那每个版本都是“稳定版”。
