### ISSUE TITLE
Intel NUC机器无法从SD卡启动

### ISSUE THREAD

**Issue by accountgd** [SuLingGG/OpenWrt-Rpi#97]
Intel NUC 机器无法从SD卡启动系统可以内置对应的读卡器驱动吗？谢谢。
机器型号  Intel NUC5PPYH

**Comment by SuLingGG** [comment]
有尝试过 UEFI 镜像吗？

openwrt-x86-64-generic-squashfs-combined-efi.img.gz

参考链接: <https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=3101984>
