### ISSUE TITLE
未保存的配置

### ISSUE THREAD

**Issue by cadyrayller** [SuLingGG/OpenWrt-Rpi#98]
未保存的配置，我保存@应用还是原来一样没保存，怎么还是显示一样数字了
![Snipaste_2021-03-03_05-46-20](https://user-images.githubusercontent.com/64737594/109719588-d407b680-7be3-11eb-9a02-ae87bd9ac55d.png)

**Comment by cadyrayller** [comment]
未保存的配置: 7我已经保存还是出现这个问题，未保存

**Comment by cadyrayller** [comment]
2021-3-1-bcm27xx-bcm2710-openwrt-bcm27xx-bcm2710-rpi-3-ext4-sysupgrade.img 树莓派3B版本的

**Comment by SuLingGG** [comment]
建议按这里的方法试一下:
<https://openwrt.cc/restore/>
